/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRoutesRouteRouteImport } from './routes/(authenticated-routes)/route'
import { Route as guestRoutesRouteRouteImport } from './routes/(guest-routes)/route'
import { Route as publicRoutesRouteRouteImport } from './routes/(public-routes)/route'
import { Route as authenticatedRoutesexistingUserRouteRouteImport } from './routes/(authenticated-routes)/(existing-user)/route'
import { Route as authenticatedRoutesnewUserRouteRouteImport } from './routes/(authenticated-routes)/(new-user)/route'
import { Route as guestRoutessignInRouteRouteImport } from './routes/(guest-routes)/(sign-in)/route'
import { Route as publicRoutesIndexRouteImport } from './routes/(public-routes)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedRoutesexistingUserUserNameIndexRouteImport } from './routes/(authenticated-routes)/(existing-user)/$userName/index'
import { Route as authenticatedRoutesnewUserWelcomeIndexRouteImport } from './routes/(authenticated-routes)/(new-user)/welcome/index'
import { Route as authenticatedRoutesredirectionRoutesRedirectionIndexRouteImport } from './routes/(authenticated-routes)/(redirection-routes)/redirection/index'
import { Route as guestRoutessignInLogInIndexRouteImport } from './routes/(guest-routes)/(sign-in)/log-in/index'
import { Route as guestRoutessignInSignUpIndexRouteImport } from './routes/(guest-routes)/(sign-in)/sign-up/index'

const authenticatedRoutesRouteRoute =
  authenticatedRoutesRouteRouteImport.update({
    id: '/(authenticated-routes)',
    getParentRoute: () => rootRouteImport,
  } as any)
const guestRoutesRouteRoute = guestRoutesRouteRouteImport.update({
  id: '/(guest-routes)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRoutesRouteRoute = publicRoutesRouteRouteImport.update({
  id: '/(public-routes)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoutesexistingUserRouteRoute =
  authenticatedRoutesexistingUserRouteRouteImport.update({
    id: '/(existing-user)',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)
const authenticatedRoutesnewUserRouteRoute =
  authenticatedRoutesnewUserRouteRouteImport.update({
    id: '/(new-user)',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)
const guestRoutessignInRouteRoute = guestRoutessignInRouteRouteImport.update({
  id: '/(sign-in)',
  getParentRoute: () => guestRoutesRouteRoute,
} as any)
const publicRoutesIndexRoute = publicRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRoutesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoutesexistingUserUserNameIndexRoute =
  authenticatedRoutesexistingUserUserNameIndexRouteImport.update({
    id: '/$userName/',
    path: '/$userName/',
    getParentRoute: () => authenticatedRoutesexistingUserRouteRoute,
  } as any)
const authenticatedRoutesnewUserWelcomeIndexRoute =
  authenticatedRoutesnewUserWelcomeIndexRouteImport.update({
    id: '/welcome/',
    path: '/welcome/',
    getParentRoute: () => authenticatedRoutesnewUserRouteRoute,
  } as any)
const authenticatedRoutesredirectionRoutesRedirectionIndexRoute =
  authenticatedRoutesredirectionRoutesRedirectionIndexRouteImport.update({
    id: '/(redirection-routes)/redirection/',
    path: '/redirection/',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)
const guestRoutessignInLogInIndexRoute =
  guestRoutessignInLogInIndexRouteImport.update({
    id: '/log-in/',
    path: '/log-in/',
    getParentRoute: () => guestRoutessignInRouteRoute,
  } as any)
const guestRoutessignInSignUpIndexRoute =
  guestRoutessignInSignUpIndexRouteImport.update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => guestRoutessignInRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$userName/': typeof authenticatedRoutesexistingUserUserNameIndexRoute
  '/welcome/': typeof authenticatedRoutesnewUserWelcomeIndexRoute
  '/redirection/': typeof authenticatedRoutesredirectionRoutesRedirectionIndexRoute
  '/log-in/': typeof guestRoutessignInLogInIndexRoute
  '/sign-up/': typeof guestRoutessignInSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$userName': typeof authenticatedRoutesexistingUserUserNameIndexRoute
  '/welcome': typeof authenticatedRoutesnewUserWelcomeIndexRoute
  '/redirection': typeof authenticatedRoutesredirectionRoutesRedirectionIndexRoute
  '/log-in': typeof guestRoutessignInLogInIndexRoute
  '/sign-up': typeof guestRoutessignInSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated-routes)': typeof authenticatedRoutesRouteRouteWithChildren
  '/(guest-routes)': typeof guestRoutesRouteRouteWithChildren
  '/(public-routes)': typeof publicRoutesRouteRouteWithChildren
  '/(authenticated-routes)/(existing-user)': typeof authenticatedRoutesexistingUserRouteRouteWithChildren
  '/(authenticated-routes)/(new-user)': typeof authenticatedRoutesnewUserRouteRouteWithChildren
  '/(guest-routes)/(sign-in)': typeof guestRoutessignInRouteRouteWithChildren
  '/(public-routes)/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated-routes)/(existing-user)/$userName/': typeof authenticatedRoutesexistingUserUserNameIndexRoute
  '/(authenticated-routes)/(new-user)/welcome/': typeof authenticatedRoutesnewUserWelcomeIndexRoute
  '/(authenticated-routes)/(redirection-routes)/redirection/': typeof authenticatedRoutesredirectionRoutesRedirectionIndexRoute
  '/(guest-routes)/(sign-in)/log-in/': typeof guestRoutessignInLogInIndexRoute
  '/(guest-routes)/(sign-in)/sign-up/': typeof guestRoutessignInSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/$userName/'
    | '/welcome/'
    | '/redirection/'
    | '/log-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/$userName'
    | '/welcome'
    | '/redirection'
    | '/log-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/(authenticated-routes)'
    | '/(guest-routes)'
    | '/(public-routes)'
    | '/(authenticated-routes)/(existing-user)'
    | '/(authenticated-routes)/(new-user)'
    | '/(guest-routes)/(sign-in)'
    | '/(public-routes)/'
    | '/api/auth/$'
    | '/(authenticated-routes)/(existing-user)/$userName/'
    | '/(authenticated-routes)/(new-user)/welcome/'
    | '/(authenticated-routes)/(redirection-routes)/redirection/'
    | '/(guest-routes)/(sign-in)/log-in/'
    | '/(guest-routes)/(sign-in)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRoutesRouteRoute: typeof authenticatedRoutesRouteRouteWithChildren
  guestRoutesRouteRoute: typeof guestRoutesRouteRouteWithChildren
  publicRoutesRouteRoute: typeof publicRoutesRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated-routes)': {
      id: '/(authenticated-routes)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest-routes)': {
      id: '/(guest-routes)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public-routes)': {
      id: '/(public-routes)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)/(existing-user)': {
      id: '/(authenticated-routes)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRoutesexistingUserRouteRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
    '/(authenticated-routes)/(new-user)': {
      id: '/(authenticated-routes)/(new-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRoutesnewUserRouteRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
    '/(guest-routes)/(sign-in)': {
      id: '/(guest-routes)/(sign-in)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRoutessignInRouteRouteImport
      parentRoute: typeof guestRoutesRouteRoute
    }
    '/(public-routes)/': {
      id: '/(public-routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRoutesIndexRouteImport
      parentRoute: typeof publicRoutesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)/(existing-user)/$userName/': {
      id: '/(authenticated-routes)/(existing-user)/$userName/'
      path: '/$userName'
      fullPath: '/$userName/'
      preLoaderRoute: typeof authenticatedRoutesexistingUserUserNameIndexRouteImport
      parentRoute: typeof authenticatedRoutesexistingUserRouteRoute
    }
    '/(authenticated-routes)/(new-user)/welcome/': {
      id: '/(authenticated-routes)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof authenticatedRoutesnewUserWelcomeIndexRouteImport
      parentRoute: typeof authenticatedRoutesnewUserRouteRoute
    }
    '/(authenticated-routes)/(redirection-routes)/redirection/': {
      id: '/(authenticated-routes)/(redirection-routes)/redirection/'
      path: '/redirection'
      fullPath: '/redirection/'
      preLoaderRoute: typeof authenticatedRoutesredirectionRoutesRedirectionIndexRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
    '/(guest-routes)/(sign-in)/log-in/': {
      id: '/(guest-routes)/(sign-in)/log-in/'
      path: '/log-in'
      fullPath: '/log-in/'
      preLoaderRoute: typeof guestRoutessignInLogInIndexRouteImport
      parentRoute: typeof guestRoutessignInRouteRoute
    }
    '/(guest-routes)/(sign-in)/sign-up/': {
      id: '/(guest-routes)/(sign-in)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof guestRoutessignInSignUpIndexRouteImport
      parentRoute: typeof guestRoutessignInRouteRoute
    }
  }
}

interface authenticatedRoutesexistingUserRouteRouteChildren {
  authenticatedRoutesexistingUserUserNameIndexRoute: typeof authenticatedRoutesexistingUserUserNameIndexRoute
}

const authenticatedRoutesexistingUserRouteRouteChildren: authenticatedRoutesexistingUserRouteRouteChildren =
  {
    authenticatedRoutesexistingUserUserNameIndexRoute:
      authenticatedRoutesexistingUserUserNameIndexRoute,
  }

const authenticatedRoutesexistingUserRouteRouteWithChildren =
  authenticatedRoutesexistingUserRouteRoute._addFileChildren(
    authenticatedRoutesexistingUserRouteRouteChildren,
  )

interface authenticatedRoutesnewUserRouteRouteChildren {
  authenticatedRoutesnewUserWelcomeIndexRoute: typeof authenticatedRoutesnewUserWelcomeIndexRoute
}

const authenticatedRoutesnewUserRouteRouteChildren: authenticatedRoutesnewUserRouteRouteChildren =
  {
    authenticatedRoutesnewUserWelcomeIndexRoute:
      authenticatedRoutesnewUserWelcomeIndexRoute,
  }

const authenticatedRoutesnewUserRouteRouteWithChildren =
  authenticatedRoutesnewUserRouteRoute._addFileChildren(
    authenticatedRoutesnewUserRouteRouteChildren,
  )

interface authenticatedRoutesRouteRouteChildren {
  authenticatedRoutesexistingUserRouteRoute: typeof authenticatedRoutesexistingUserRouteRouteWithChildren
  authenticatedRoutesnewUserRouteRoute: typeof authenticatedRoutesnewUserRouteRouteWithChildren
  authenticatedRoutesredirectionRoutesRedirectionIndexRoute: typeof authenticatedRoutesredirectionRoutesRedirectionIndexRoute
}

const authenticatedRoutesRouteRouteChildren: authenticatedRoutesRouteRouteChildren =
  {
    authenticatedRoutesexistingUserRouteRoute:
      authenticatedRoutesexistingUserRouteRouteWithChildren,
    authenticatedRoutesnewUserRouteRoute:
      authenticatedRoutesnewUserRouteRouteWithChildren,
    authenticatedRoutesredirectionRoutesRedirectionIndexRoute:
      authenticatedRoutesredirectionRoutesRedirectionIndexRoute,
  }

const authenticatedRoutesRouteRouteWithChildren =
  authenticatedRoutesRouteRoute._addFileChildren(
    authenticatedRoutesRouteRouteChildren,
  )

interface guestRoutessignInRouteRouteChildren {
  guestRoutessignInLogInIndexRoute: typeof guestRoutessignInLogInIndexRoute
  guestRoutessignInSignUpIndexRoute: typeof guestRoutessignInSignUpIndexRoute
}

const guestRoutessignInRouteRouteChildren: guestRoutessignInRouteRouteChildren =
  {
    guestRoutessignInLogInIndexRoute: guestRoutessignInLogInIndexRoute,
    guestRoutessignInSignUpIndexRoute: guestRoutessignInSignUpIndexRoute,
  }

const guestRoutessignInRouteRouteWithChildren =
  guestRoutessignInRouteRoute._addFileChildren(
    guestRoutessignInRouteRouteChildren,
  )

interface guestRoutesRouteRouteChildren {
  guestRoutessignInRouteRoute: typeof guestRoutessignInRouteRouteWithChildren
}

const guestRoutesRouteRouteChildren: guestRoutesRouteRouteChildren = {
  guestRoutessignInRouteRoute: guestRoutessignInRouteRouteWithChildren,
}

const guestRoutesRouteRouteWithChildren =
  guestRoutesRouteRoute._addFileChildren(guestRoutesRouteRouteChildren)

interface publicRoutesRouteRouteChildren {
  publicRoutesIndexRoute: typeof publicRoutesIndexRoute
}

const publicRoutesRouteRouteChildren: publicRoutesRouteRouteChildren = {
  publicRoutesIndexRoute: publicRoutesIndexRoute,
}

const publicRoutesRouteRouteWithChildren =
  publicRoutesRouteRoute._addFileChildren(publicRoutesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoutesRouteRoute: authenticatedRoutesRouteRouteWithChildren,
  guestRoutesRouteRoute: guestRoutesRouteRouteWithChildren,
  publicRoutesRouteRoute: publicRoutesRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
