/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfieRouteImport } from './routes/selfie'
import { Route as publicRoutesIndexRouteImport } from './routes/(public-routes)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SelfieRoute = SelfieRouteImport.update({
  id: '/selfie',
  path: '/selfie',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRoutesIndexRoute = publicRoutesIndexRouteImport.update({
  id: '/(public-routes)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/selfie': typeof SelfieRoute
  '/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/selfie': typeof SelfieRoute
  '/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/selfie': typeof SelfieRoute
  '/(public-routes)/': typeof publicRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/selfie' | '/' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/selfie' | '/' | '/api/auth/$'
  id: '__root__' | '/selfie' | '/(public-routes)/' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SelfieRoute: typeof SelfieRoute
  publicRoutesIndexRoute: typeof publicRoutesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selfie': {
      id: '/selfie'
      path: '/selfie'
      fullPath: '/selfie'
      preLoaderRoute: typeof SelfieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public-routes)/': {
      id: '/(public-routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SelfieRoute: SelfieRoute,
  publicRoutesIndexRoute: publicRoutesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
