import {
  boolean,
  char,
  date,
  decimal,
  index,
  int,
  json,
  mysqlTable,
  primaryKey,
  text,
  time,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";
import {
  approvalStatusEnum,
  batchStatusEnum,
  collectionStatusEnum,
  customerTypeEnum,
  dayStatusEnum,
  fulfillmentStatusEnum,
  inventoryMovementTypeEnum,
  orderStatusEnum,
  orderTypeEnum,
  paymentMethodEnum,
  paymentStatusEnum,
  routeOwnershipEnum,
  stockTransferStatusEnum,
  travelModeEnum,
  userRoleEnum,
  userStatusEnum,
  visitOutcomeEnum,
} from "./enums";
import { relations } from "drizzle-orm";
import { id } from "@repo/utils/id";

/**
 * OrganizationsTable
 *
 * Represents a tenant/company using the application.
 *
 * This is the top-level entity for the multi-tenant system. Most business
 * data belongs to an organization and is isolated using organizationId.
 *
 * Stores:
 * - Company/organization identity
 * - Contact information
 * - Registered address
 * - GSTIN/PAN details
 * - Active/inactive status
 *
 * Relationships:
 * - Has many users, territories, routes, stockists, customers, products,
 *   inventory records, orders, payments, audit logs, and settings.
 */

export const OrganizationsTable = mysqlTable(
  "organizations",
  {
    id: autoGeneratedId(),
    name: varchar("name", { length: 255 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    email: varchar("email", { length: 255 }).unique().notNull(),
    phone: varchar("phone", { length: 15 }),
    address: text("address"),
    pinCode: char("pin_code", { length: 6 }),
    gstin: varchar("gstin", { length: 20 }),
    pan: varchar("pan", { length: 20 }),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("ORGN"),
  },
  (table) => [uniqueIndex("organizations_code_unique").on(table.code)],
);

export const OrganizationRelations = relations(
  OrganizationsTable,
  ({ many }) => ({
    users: many(UsersTable),
    mediaFiles: many(MediaFilesTable),
    territories: many(TerritoriesTable),
    routes: many(RoutesTable),
    stockists: many(StockistsTable),
    customers: many(CustomersTable),
    productCategories: many(ProductCategoriesTable),
    products: many(ProductsTable),
    masterInventory: many(MasterInventoryTable),
    inventoryMovements: many(InventoryMovementsTable),
    stockTransfers: many(StockTransfersTable),
    fieldDays: many(FieldDaysTable),
    orders: many(OrdersTable),
    payments: many(PaymentsTable),
    auditLogs: many(AuditLogsTable),
    settings: many(OrganizationSettingsTable),
  }),
);

/**
 * UsersTable
 *
 * Represents application users/employees belonging to an organization.
 *
 * A user can perform field activities, manage customers, create orders,
 * collect payments, manage inventory, and perform other operations depending
 * on their assigned role.
 *
 * Stores:
 * - User identity and contact information
 * - Login credentials
 * - Employee code
 * - Role and account status
 * - Profile/avatar information
 * - Last login information
 *
 * Relationships:
 * - Belongs to an organization
 * - Can be assigned territories, routes, and stockists
 * - Can create customers, visits, orders, payments, and inventory movements
 * - Can approve/review various operational requests
 */

export const UsersTable = mysqlTable(
  "users",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", { length: 10 }),
    role: userRoleEnum("role").notNull(),
    name: varchar("name", { length: 150 }).notNull(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    username: varchar("username", { length: 255 }).notNull().unique(),
    phone: varchar("phone", { length: 30 }).notNull(),
    passwordHash: text("password_hash"),
    employeeCode: varchar("employee_code", { length: 50 }),
    status: userStatusEnum("status").default("UNDER_VERIFICATION").notNull(),
    avatarUrl: text("avatar_url"),
    lastLoginAt: timestamp("last_login_at"),

    ...tableMetaData("USER"),
  },
  (table) => [
    index("users_employee_code_idx").on(
      table.organizationId,
      table.employeeCode,
    ),
  ],
);

export const UserRelations = relations(UsersTable, ({ one, many }) => ({
  organization: one(OrganizationsTable, {
    fields: [UsersTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  mediaFiles: many(MediaFilesTable),
  userTerritories: many(UserTerritoriesTable),
  userRoutes: many(UserRoutesTable),
  userStockists: many(UserStockistsTable),
  createdCustomers: many(CustomersTable),
  fieldDays: many(FieldDaysTable),
  visits: many(VisitsTable),
  orders: many(OrdersTable),
  inventoryMovements: many(InventoryMovementsTable),
  daysUnlocked: many(DayUnlockRequestsTable),
  payments: many(PaymentsTable),
  collectionHandovers: many(CollectionHandoversTable),
  expiryWastageEntries: many(ExpiryWastageEntriesTable),
  customerFollowUps: many(CustomerFollowUpsTable),
  auditLogs: many(AuditLogsTable),
}));

/**
 * MediaFilesTable
 *
 * Central storage reference for uploaded files and images.
 *
 * Instead of storing files directly in business tables, this table stores
 * metadata and the URL/reference required to access the uploaded file.
 *
 * Typical examples:
 * - Profile avatars
 * - Product images
 * - Opening/closing odometer photos
 * - Field-day selfies
 * - Visit photos
 * - Documents
 *
 * Stores:
 * - File URL and name
 * - MIME type and file size
 * - Image dimensions
 * - Additional provider/file metadata
 * - Organization and uploader information
 */

export const MediaFilesTable = mysqlTable("media_files", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", { length: 10 })
    .notNull()
    .references(() => OrganizationsTable.id, {
      onUpdate: "cascade",
      onDelete: "cascade",
    }),
  uploadedBy: char("uploaded_by", { length: 10 }).references(
    () => UsersTable.id,
    {
      onUpdate: "cascade",
      onDelete: "set null",
    },
  ),
  url: text("url").notNull(),
  fileName: varchar("file_name", { length: 255 }),
  mimeType: varchar("mime_type", { length: 100 }),
  fileSize: int("file_size"),
  width: int("width"),
  height: int("height"),
  metadata: json("metadata"),

  ...tableMetaData("MDFL"),
});

export const MediaFilesRelations = relations(
  MediaFilesTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [MediaFilesTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    uploader: one(UsersTable, {
      fields: [MediaFilesTable.uploadedBy],
      references: [UsersTable.id],
    }),
    productMedia: many(ProductMediaTable),
    fieldDaysOpeningOdometer: many(FieldDaysTable),
    fieldDaysClosingOdometer: many(FieldDaysTable),
    fieldDaysStartSelfie: many(FieldDaysTable),
    fieldDaysEndSelfie: many(FieldDaysTable),
    visits: many(VisitsTable),
  }),
);

/**
 * TerritoriesTable
 *
 * Represents a geographical/business territory managed by the organization.
 *
 * TerritoriesTable provide a higher-level geographical grouping for routes,
 * customers, and field representatives.
 *
 * Examples:
 * - Kolkata North
 * - Midnapore
 * - Kharagpur
 * - Howrah
 *
 * Stores:
 * - Territory name and code
 * - State, district, city, and PIN code
 * - Active/inactive status
 *
 * Relationships:
 * - Belongs to an organization
 * - Contains routes
 * - Can be assigned to multiple users
 * - Can be associated with customer assignments
 */

export const TerritoriesTable = mysqlTable(
  "territories",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", { length: 10 })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    name: varchar("name", { length: 150 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    state: varchar("state", { length: 100 }),
    district: varchar("district", { length: 100 }),
    city: varchar("city", { length: 100 }),
    pinCode: varchar("pin_code", { length: 10 }),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("TRTS"),
  },
  (table) => [
    uniqueIndex("territories_org_code_unique").on(
      table.organizationId,
      table.code,
    ),
  ],
);

export const TerritoriesRelations = relations(
  TerritoriesTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [TerritoriesTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    routes: many(RoutesTable),
    userTerritories: many(UserTerritoriesTable),
    customerAssignments: many(CustomerAssignmentsTable),
  }),
);

/**
 * RoutesTable
 *
 * Represents a geographical route within a territory, used for field activities.
 *
 * RoutesTable define the path that field representatives follow to serve customers.
 *
 * Stores:
 * - Route name and code
 * - Ownership information
 * - Active/inactive status
 * - Organization and territory associations
 *
 * Relationships:
 * - Belongs to an organization and territory
 * - Can be assigned to multiple users
 * - Contains stops and customer assignments
 * - Can have associated visits and orders
 */

export const RoutesTable = mysqlTable(
  "routes",
  {
    id: autoGeneratedId(),
    isActive: boolean("is_active").default(true).notNull(),
    name: varchar("name", { length: 150 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    ownership: routeOwnershipEnum("ownership").notNull(),
    distributorId: char("distributor_id", {
      length: 10,
    }),
    organizationId: char("organization_id", { length: 10 })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    territoryId: char("territory_id", { length: 10 })
      .notNull()
      .references(() => TerritoriesTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),

    ...tableMetaData("ROUT"),
  },
  (table) => [
    uniqueIndex("routes_org_code_unique").on(table.organizationId, table.code),
    index("routes_territory_idx").on(table.territoryId),
  ],
);

export const RoutesRelations = relations(RoutesTable, ({ one, many }) => ({
  territory: one(TerritoriesTable, {
    fields: [RoutesTable.territoryId],
    references: [TerritoriesTable.id],
  }),
  organization: one(OrganizationsTable, {
    fields: [RoutesTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  userRoutes: many(UserRoutesTable),
  routeStops: many(RouteStopsTable),
  customerAssignments: many(CustomerAssignmentsTable),
  visits: many(VisitsTable),
  orders: many(OrdersTable),
}));

/**
 * UserTerritoriesTable
 *
 * Junction table that maps users/field representatives to territories.
 *
 * This supports a many-to-many relationship where:
 * - One user can work in multiple territories.
 * - One territory can have multiple users.
 *
 * Stores:
 * - User and territory association
 * - Assignment validity period
 * - Whether the territory is the user's primary territory
 *
 * The date fields allow historical and future assignments to be maintained.
 */

export const UserTerritoriesTable = mysqlTable(
  "user_territories",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "cascade",
      }),
    territoryId: char("territory_id", { length: 10 })
      .notNull()
      .references(() => TerritoriesTable.id, {
        onDelete: "cascade",
      }),
    assignedFrom: date("assigned_from"),
    assignedTo: date("assigned_to"),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USTE"),
  },
  (table) => [
    primaryKey({
      name: "useers_assigned_territories",
      columns: [table.userId, table.territoryId],
    }),
  ],
);

/**
 * UserRoutesTable
 *
 * Junction table that maps users/field representatives to routes.
 *
 * This supports a many-to-many relationship where:
 * - One user can be assigned to multiple routes.
 * - One route can have multiple users assigned.
 *
 * Stores:
 * - User and route association
 * - Assignment validity period
 * - Whether the route is the user's primary route
 *
 * The date fields allow historical and future assignments to be maintained.
 */

export const UserRoutesTable = mysqlTable(
  "user_routes",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "cascade",
      }),
    routeId: char("route_id", { length: 10 })
      .notNull()
      .references(() => RoutesTable.id, {
        onDelete: "cascade",
      }),
    assignedFrom: date("assigned_from"),
    assignedTo: date("assigned_to"),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USRT"),
  },
  (table) => [
    primaryKey({
      name: "useers_assigned_routes",
      columns: [table.userId, table.routeId],
    }),
  ],
);

export const UserRoutesRelations = relations(UserRoutesTable, ({ one }) => ({
  user: one(UsersTable, {
    fields: [UserRoutesTable.userId],
    references: [UsersTable.id],
  }),
  route: one(RoutesTable, {
    fields: [UserRoutesTable.routeId],
    references: [RoutesTable.id],
  }),
}));

export const UserTerritoriesRelations = relations(
  UserTerritoriesTable,
  ({ one }) => ({
    user: one(UsersTable, {
      fields: [UserTerritoriesTable.userId],
      references: [UsersTable.id],
    }),
    territory: one(TerritoriesTable, {
      fields: [UserTerritoriesTable.territoryId],
      references: [TerritoriesTable.id],
    }),
  }),
);

/**
 * RouteStopsTable
 *
 * Represents an individual customer stop within a route.
 *
 * A route contains multiple stops, and the sequence field determines the
 * planned visit order.
 *
 * Stores:
 * - Route association
 * - Customer association
 * - Visit sequence/order
 * - Expected visit duration
 * - Active/inactive status
 *
 * Example:
 * Route A:
 *   1. Doctor A
 *   2. Doctor B
 *   3. Chemist C
 *
 * This table represents those individual planned stops.
 */

export const RouteStopsTable = mysqlTable(
  "route_stops",
  {
    id: autoGeneratedId(),
    routeId: char("route_id", { length: 10 })
      .notNull()
      .references(() => RoutesTable.id, {
        onDelete: "cascade",
      }),
    customerId: char("customer_id", { length: 10 })
      .notNull()
      .references(() => CustomersTable.id, {
        onDelete: "cascade",
      }),
    sequence: int("sequence").notNull(),
    plannedVisitDurationMinutes: int("planned_visit_duration_minutes"),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("RUST"),
  },
  (table) => [
    uniqueIndex("route_stops_route_sequence_unique").on(
      table.routeId,
      table.sequence,
    ),
    index("route_stops_route_customer_idx").on(table.routeId, table.customerId),
  ],
);

export const RouteStopsRelations = relations(RouteStopsTable, ({ one }) => ({
  route: one(RoutesTable, {
    fields: [RouteStopsTable.routeId],
    references: [RoutesTable.id],
  }),
  customer: one(CustomersTable, {
    fields: [RouteStopsTable.customerId],
    references: [CustomersTable.id],
  }),
}));

/**
 * StockistsTable
 *
 * Represents distributors, stockists, or other inventory-holding business
 * partners associated with an organization.
 *
 * A stockist can hold pharmaceutical/product inventory and may be responsible
 * for fulfilling orders generated by field representatives.
 *
 * Stores:
 * - Business identity and contact details
 * - Address/location information
 * - Drug license information
 * - GSTIN/PAN
 * - Distributor flag
 * - Active/inactive status
 *
 * The isDistributor field allows the same table to support different types
 * of inventory/channel partners.
 */

export const StockistsTable = mysqlTable(
  "stockists",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    name: varchar("name", { length: 200 }).notNull(),
    code: varchar("code", { length: 50 }),
    phone: varchar("phone", { length: 30 }),
    email: varchar("email", { length: 255 }).notNull().unique(),
    address: text("address"),
    city: varchar("city", { length: 100 }),
    district: varchar("district", { length: 100 }),
    state: varchar("state", { length: 100 }),
    pinCode: varchar("pin_code", { length: 10 }),
    drugLicenseNumber: varchar("drug_license_number", {
      length: 100,
    }),
    gstin: varchar("gstin", { length: 20 }),
    pan: varchar("pan", { length: 20 }),
    isDistributor: boolean("is_distributor").default(false).notNull(),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("STKT"),
  },
  (table) => [
    uniqueIndex("stockists_org_code_unique").on(
      table.organizationId,
      table.code,
    ),
  ],
);

export const StockistsRelations = relations(
  StockistsTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [StockistsTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    userStockists: many(UserStockistsTable),
    productPrices: many(ProductPricesTable),
    stockistInventory: many(StockistInventoryTable),
    inventoryMovements: many(InventoryMovementsTable),
    stockTransfersFrom: many(StockTransfersTable),
    stockTransfersTo: many(StockTransfersTable),
    collectionHandovers: many(CollectionHandoversTable),
    expiryWastageEntries: many(ExpiryWastageEntriesTable),
  }),
);

/**
 * UserStockistsTable
 *
 * Junction table mapping users/field representatives to stockists.
 *
 * This defines which stockists a user is allowed or expected to work with.
 *
 * Supports:
 * - One user → multiple stockists
 * - One stockist → multiple users
 *
 * The primary flag can identify the user's main/default stockist.
 */

export const UserStockistsTable = mysqlTable(
  "user_stockists",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "cascade",
      }),
    stockistId: char("stockist_id", { length: 10 })
      .notNull()
      .references(() => StockistsTable.id, {
        onDelete: "cascade",
      }),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USSK"),
  },
  (table) => [
    primaryKey({
      name: "user_stockist",
      columns: [table.userId, table.stockistId],
    }),
  ],
);

export const UserStockistsRelations = relations(
  UserStockistsTable,
  ({ one }) => ({
    user: one(UsersTable, {
      fields: [UserStockistsTable.userId],
      references: [UsersTable.id],
    }),
    stockist: one(StockistsTable, {
      fields: [UserStockistsTable.stockistId],
      references: [StockistsTable.id],
    }),
  }),
);

/**
 * CustomersTable
 *
 * Central master table for business customers such as doctors, chemists,
 * pharmacies, hospitals, clinics, or other customer types.
 *
 * The customer type determines what additional information is applicable.
 *
 * Stores:
 * - Customer identity and contact details
 * - Address and geographical coordinates
 * - Drug license/GSTIN/PAN information
 * - Customer type
 * - Active/inactive status
 * - User who created the customer
 *
 * This is one of the core tables of the field-sales system and is referenced
 * by assignments, visits, orders, payments, follow-ups, and doctor-specific
 * data.
 */

export const CustomersTable = mysqlTable(
  "customers",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    type: customerTypeEnum("type").notNull(),
    name: varchar("name", { length: 200 }).notNull(),
    primaryMobile: varchar("primary_mobile", {
      length: 30,
    }).notNull(),
    secondaryMobile: varchar("secondary_mobile", {
      length: 30,
    }),
    email: varchar("email", { length: 255 }).notNull().unique(),
    address: text("address"),
    pinCode: varchar("pin_code", { length: 10 }),
    drugLicenseNumber: varchar("drug_license_number", {
      length: 100,
    }),
    panNumber: varchar("pan_number", {
      length: 20,
    }),
    gstin: varchar("gstin", {
      length: 20,
    }),
    latitude: decimal("latitude", {
      precision: 10,
      scale: 7,
    }),
    longitude: decimal("longitude", {
      precision: 10,
      scale: 7,
    }),
    isActive: boolean("is_active").default(true).notNull(),
    createdBy: char("created_by", {
      length: 10,
    }).references(() => UsersTable.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("CUST"),
  },
  (table) => [
    uniqueIndex("customers_org_primary_mobile_unique").on(
      table.organizationId,
      table.primaryMobile,
    ),
    index("customers_secondary_mobile_idx").on(
      table.organizationId,
      table.secondaryMobile,
    ),
    index("customers_location_idx").on(table.latitude, table.longitude),
  ],
);

export const CustomersRelations = relations(
  CustomersTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [CustomersTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    creator: one(UsersTable, {
      fields: [CustomersTable.createdBy],
      references: [UsersTable.id],
    }),
    routeStops: many(RouteStopsTable),
    customerAssignments: many(CustomerAssignmentsTable),
    doctorProfile: many(DoctorProfilesTable),
    doctorAvailability: many(DoctorAvailabilityTable),
    doctorProductPreferences: many(DoctorProductPreferencesTable),
    visits: many(VisitsTable),
    orders: many(OrdersTable),
    payments: many(PaymentsTable),
    customerFollowUps: many(CustomerFollowUpsTable),
  }),
);

/**
 * CustomerAssignmentsTable
 *
 * Stores the assignment of customers to territories, routes, and users.
 *
 * This table answers questions such as:
 * - Which territory does this customer belong to?
 * - Which route should the customer appear on?
 * - Which field representative is responsible for the customer?
 * - When was the assignment active?
 *
 * Historical assignments can be preserved using assignedFrom/assignedTo.
 */

export const CustomerAssignmentsTable = mysqlTable("customer_assignments", {
  id: autoGeneratedId(),
  customerId: char("customer_id", {
    length: 10,
  })
    .notNull()
    .references(() => CustomersTable.id, {
      onDelete: "cascade",
    }),
  territoryId: char("territory_id", {
    length: 10,
  }).references(() => TerritoriesTable.id, {
    onDelete: "set null",
  }),
  routeId: char("route_id", {
    length: 10,
  }).references(() => RoutesTable.id, {
    onDelete: "set null",
  }),
  assignedToUserId: char("assigned_to_user_id", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  assignedFrom: date("assigned_from"),
  assignedTo: date("assigned_to"),
  isActive: boolean("is_active").default(true).notNull(),

  ...tableMetaData("CUAS"),
});

export const CustomerAssignmentsRelations = relations(
  CustomerAssignmentsTable,
  ({ one }) => ({
    customer: one(CustomersTable, {
      fields: [CustomerAssignmentsTable.customerId],
      references: [CustomersTable.id],
    }),
    territory: one(TerritoriesTable, {
      fields: [CustomerAssignmentsTable.territoryId],
      references: [TerritoriesTable.id],
    }),
    route: one(RoutesTable, {
      fields: [CustomerAssignmentsTable.routeId],
      references: [RoutesTable.id],
    }),
    assignedToUser: one(UsersTable, {
      fields: [CustomerAssignmentsTable.assignedToUserId],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * DoctorProfilesTable
 *
 * Stores doctor-specific information for customers whose type is DOCTOR.
 *
 * This is separated from CustomersTable so that the general customer table does
 * not become filled with fields that only apply to doctors.
 *
 * Stores:
 * - Medical specialization
 * - Chamber/clinic name
 * - Consultation hours
 * - Meeting notes
 *
 * The customerId acts as both the primary key and foreign key, creating a
 * one-to-one extension of the CustomersTable record.
 */

export const DoctorProfilesTable = mysqlTable("doctor_profiles", {
  customerId: char("customer_id", { length: 10 })
    .primaryKey()
    .references(() => CustomersTable.id, {
      onDelete: "cascade",
    }),
  specialist: varchar("specialist", {
    length: 150,
  }),
  chamberName: varchar("chamber_name", {
    length: 200,
  }),
  consultationStartTime: time("consultation_start_time"),
  consultationEndTime: time("consultation_end_time"),
  meetingNotes: text("meeting_notes"),

  ...tableMetaData("DOCS"),
});

export const DoctorProfilesRelations = relations(
  DoctorProfilesTable,
  ({ one, many }) => ({
    customer: one(CustomersTable, {
      fields: [DoctorProfilesTable.customerId],
      references: [CustomersTable.id],
    }),
    availability: many(DoctorAvailabilityTable),
  }),
);

/**
 * DoctorAvailabilityTable
 *
 * Stores recurring weekly availability for doctors.
 *
 * This allows the application to determine when a doctor is normally
 * available for visits.
 *
 * Stores:
 * - Doctor/customer
 * - Day of week
 * - Start time
 * - End time
 *
 * Multiple availability windows can be stored for the same doctor and day.
 */

export const DoctorAvailabilityTable = mysqlTable("doctor_availability", {
  id: autoGeneratedId(),
  doctorId: char("doctor_id", { length: 10 })
    .notNull()
    .references(() => CustomersTable.id, {
      onDelete: "cascade",
    }),
  dayOfWeek: int("day_of_week").notNull(),
  startTime: time("start_time").notNull(),
  endTime: time("end_time").notNull(),

  ...tableMetaData("DOAV"),
});

export const DoctorAvailabilityRelations = relations(
  DoctorAvailabilityTable,
  ({ one }) => ({
    doctor: one(CustomersTable, {
      fields: [DoctorAvailabilityTable.doctorId],
      references: [CustomersTable.id],
    }),
  }),
);

/**
 * ProductCategoriesTable
 *
 * Groups products into logical business categories.
 *
 * Examples:
 * - Antibiotics
 * - Vitamins
 * - Pain Management
 * - Gastro
 * - Cardiology
 *
 * Categories make product management, filtering, reporting, and navigation
 * easier.
 */

export const ProductCategoriesTable = mysqlTable("product_categories", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrganizationsTable.id, {
      onDelete: "cascade",
    }),
  name: varchar("name", { length: 150 }).notNull(),
  description: text("description"),
  isActive: boolean("is_active").default(true).notNull(),

  ...tableMetaData("PRCT"),
});

export const ProductCategoriesRelations = relations(
  ProductCategoriesTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [ProductCategoriesTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    products: many(ProductsTable),
  }),
);

/**
 * ProductsTable
 *
 * Master catalog of products sold/distributed by the organization.
 *
 * This is the central product definition used throughout inventory, pricing,
 * orders, doctor preferences, and reporting.
 *
 * Stores:
 * - Product name and SKU
 * - Generic name
 * - Strength and dosage form
 * - Pack size and unit
 * - Product description and benefits
 * - Usage information
 * - MRP and tax rate
 * - Category and active status
 *
 * Inventory quantities are intentionally stored in separate inventory tables.
 */
export const ProductsTable = mysqlTable(
  "products",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    categoryId: char("category_id", {
      length: 10,
    }).references(() => ProductCategoriesTable.id, {
      onDelete: "set null",
    }),
    name: varchar("name", { length: 200 }).notNull(),
    sku: varchar("sku", { length: 100 }).notNull(),
    genericName: varchar("generic_name", {
      length: 200,
    }),
    strength: varchar("strength", {
      length: 100,
    }),
    dosageForm: varchar("dosage_form", {
      length: 100,
    }),
    packSize: varchar("pack_size", {
      length: 100,
    }),
    unit: varchar("unit", {
      length: 50,
    }),
    description: text("description"),
    benefits: text("benefits"),
    usageInformation: text("usage_information"),
    mrp: decimal("mrp", {
      precision: 14,
      scale: 2,
    }).notNull(),
    taxRate: decimal("tax_rate", {
      precision: 6,
      scale: 2,
    })
      .default("0")
      .notNull(),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("PROD"),
  },
  (table) => [
    uniqueIndex("products_org_sku_unique").on(table.organizationId, table.sku),
    index("products_name_idx").on(table.organizationId, table.name),
  ],
);

export const ProductsRelations = relations(ProductsTable, ({ one, many }) => ({
  organization: one(OrganizationsTable, {
    fields: [ProductsTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  category: one(ProductCategoriesTable, {
    fields: [ProductsTable.categoryId],
    references: [ProductCategoriesTable.id],
  }),
  productMedia: many(ProductMediaTable),
  doctorProductPreferences: many(DoctorProductPreferencesTable),
  productPrices: many(ProductPricesTable),
  productBatches: many(ProductBatchesTable),
  stockistInventory: many(StockistInventoryTable),
  masterInventory: many(MasterInventoryTable),
  inventoryMovements: many(InventoryMovementsTable),
  stockTransferItems: many(StockTransferItemsTable),
  orderItems: many(OrderItemsTable),
  expiryWastageEntries: many(ExpiryWastageEntriesTable),
}));

/**
 * ProductMediaTable
 *
 * Junction table connecting products with uploaded media files.
 *
 * Allows a product to have multiple images/files while keeping media storage
 * centralized in MediaFilesTable.
 *
 * Stores:
 * - Product association
 * - Media/file association
 * - Display order
 * - Primary image indicator
 */
export const ProductMediaTable = mysqlTable("product_media", {
  id: autoGeneratedId(),
  productId: char("product_id", { length: 10 })
    .notNull()
    .references(() => ProductsTable.id, {
      onDelete: "cascade",
    }),
  mediaId: char("media_id", { length: 10 })
    .notNull()
    .references(() => MediaFilesTable.id, {
      onDelete: "cascade",
    }),
  sortOrder: int("sort_order").default(0).notNull(),
  isPrimary: boolean("is_primary").default(false).notNull(),

  ...tableMetaData("PRMD"),
});

export const ProductMediaRelations = relations(
  ProductMediaTable,
  ({ one }) => ({
    product: one(ProductsTable, {
      fields: [ProductMediaTable.productId],
      references: [ProductsTable.id],
    }),
    media: one(MediaFilesTable, {
      fields: [ProductMediaTable.mediaId],
      references: [MediaFilesTable.id],
    }),
  }),
);

/**
 * DoctorProductPreferencesTable
 *
 * Stores product preferences/recommendations for individual doctors.
 *
 * This can be used by field representatives to understand which products
 * a doctor prefers, regularly prescribes, or has shown interest in.
 *
 * Stores:
 * - Doctor/customer
 * - Product
 * - Preference level
 * - Notes
 * - User who created the preference
 *
 * The composite primary key prevents duplicate doctor-product preferences.
 */

export const DoctorProductPreferencesTable = mysqlTable(
  "doctor_product_preferences",
  {
    doctorId: char("doctor_id", { length: 10 })
      .notNull()
      .references(() => CustomersTable.id, {
        onDelete: "cascade",
      }),
    productId: char("product_id", { length: 10 })
      .notNull()
      .references(() => ProductsTable.id, {
        onDelete: "cascade",
      }),
    preferenceLevel: int("preference_level").default(1).notNull(),
    notes: text("notes"),
    createdBy: char("created_by", {
      length: 10,
    }).references(() => UsersTable.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("DPPR"),
  },
  (table) => [
    primaryKey({
      name: "doctor_with_product",
      columns: [table.doctorId, table.productId],
    }),
  ],
);

export const DoctorProductPreferencesRelations = relations(
  DoctorProductPreferencesTable,
  ({ one }) => ({
    doctor: one(CustomersTable, {
      fields: [DoctorProductPreferencesTable.doctorId],
      references: [CustomersTable.id],
    }),
    product: one(ProductsTable, {
      fields: [DoctorProductPreferencesTable.productId],
      references: [ProductsTable.id],
    }),
    creator: one(UsersTable, {
      fields: [DoctorProductPreferencesTable.createdBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * ProductPricesTable
 *
 * Stores product selling prices, optionally specific to a stockist.
 *
 * Supports historical and future pricing through effectiveFrom/effectiveTo.
 *
 * This allows the system to answer:
 * - What is the current price?
 * - What was the price during a previous period?
 * - Does a specific stockist have a different price?
 *
 * A null stockistId can be used for an organization-wide/default price.
 */

export const ProductPricesTable = mysqlTable("product_prices", {
  id: autoGeneratedId(),
  productId: char("product_id", { length: 10 })
    .notNull()
    .references(() => ProductsTable.id, {
      onDelete: "cascade",
    }),
  stockistId: char("stockist_id", {
    length: 10,
  }).references(() => StockistsTable.id, {
    onDelete: "cascade",
  }),
  sellingPrice: decimal("selling_price", {
    precision: 14,
    scale: 2,
  }).notNull(),
  effectiveFrom: date("effective_from").notNull(),
  effectiveTo: date("effective_to"),

  ...tableMetaData("PRPR"),
});

export const ProductPricesRelations = relations(
  ProductPricesTable,
  ({ one }) => ({
    product: one(ProductsTable, {
      fields: [ProductPricesTable.productId],
      references: [ProductsTable.id],
    }),
    stockist: one(StockistsTable, {
      fields: [ProductPricesTable.stockistId],
      references: [StockistsTable.id],
    }),
  }),
);

/**
 * ProductBatchesTable
 *
 * Represents individual manufacturing batches of products.
 *
 * Batch-level tracking is especially important for pharmaceutical inventory
 * because expiry dates, purchase prices, and stock quantities can differ
 * between batches of the same product.
 *
 * Stores:
 * - Product association
 * - Batch number
 * - Manufacturing date
 * - Expiry date
 * - Batch-specific MRP
 * - Purchase price
 * - Batch status
 *
 * Inventory is tracked against batches rather than only against products.
 */

export const ProductBatchesTable = mysqlTable(
  "product_batches",
  {
    id: autoGeneratedId(),
    productId: char("product_id", { length: 10 })
      .notNull()
      .references(() => ProductsTable.id, {
        onDelete: "restrict",
      }),
    batchNumber: varchar("batch_number", {
      length: 100,
    }).notNull(),
    manufacturingDate: date("manufacturing_date"),
    expiryDate: date("expiry_date").notNull(),
    mrp: decimal("mrp", {
      precision: 14,
      scale: 2,
    }).notNull(),
    purchasePrice: decimal("purchase_price", {
      precision: 14,
      scale: 2,
    }),
    status: batchStatusEnum("status").default("ACTIVE").notNull(),

    ...tableMetaData("PRBT"),
  },
  (table) => [
    uniqueIndex("product_batches_product_batch_unique").on(
      table.productId,
      table.batchNumber,
    ),
    index("product_batches_expiry_idx").on(table.expiryDate),
  ],
);

export const ProductBatchesRelations = relations(
  ProductBatchesTable,
  ({ one, many }) => ({
    product: one(ProductsTable, {
      fields: [ProductBatchesTable.productId],
      references: [ProductsTable.id],
    }),
    stockistInventory: many(StockistInventoryTable),
    masterInventory: many(MasterInventoryTable),
    inventoryMovements: many(InventoryMovementsTable),
    stockTransferItems: many(StockTransferItemsTable),
    orderItems: many(OrderItemsTable),
    expiryWastageEntries: many(ExpiryWastageEntriesTable),
  }),
);

/**
 * StockistInventoryTable
 *
 * Represents the current inventory held by a stockist for a specific batch.
 *
 * Each record represents:
 *   Stockist + Batch
 *
 * Stores:
 * - Available quantity
 * - Reserved quantity
 * - Stockist
 * - Product
 * - Batch
 *
 * Reserved quantity represents stock already committed to orders but not
 * yet fully dispatched/delivered.
 */

export const StockistInventoryTable = mysqlTable(
  "stockist_inventory",
  {
    id: autoGeneratedId(),
    stockistId: char("stockist_id", {
      length: 10,
    })
      .notNull()
      .references(() => StockistsTable.id, {
        onDelete: "cascade",
      }),
    productId: char("product_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductsTable.id, {
        onDelete: "cascade",
      }),
    batchId: char("batch_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductBatchesTable.id, {
        onDelete: "restrict",
      }),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),
    reservedQuantity: decimal("reserved_quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),

    ...tableMetaData("SKIV"),
  },
  (table) => [
    uniqueIndex("stockist_inventory_unique").on(
      table.stockistId,
      table.batchId,
    ),
    index("stockist_inventory_product_idx").on(
      table.stockistId,
      table.productId,
    ),
  ],
);

export const StockistInventoryRelations = relations(
  StockistInventoryTable,
  ({ one }) => ({
    stockist: one(StockistsTable, {
      fields: [StockistInventoryTable.stockistId],
      references: [StockistsTable.id],
    }),
    product: one(ProductsTable, {
      fields: [StockistInventoryTable.productId],
      references: [ProductsTable.id],
    }),
    batch: one(ProductBatchesTable, {
      fields: [StockistInventoryTable.batchId],
      references: [ProductBatchesTable.id],
    }),
  }),
);

/**
 * MasterInventoryTable
 *
 * Represents the inventory held at the master/company warehouse level.
 *
 * This table tracks the total available and reserved quantities of products
 * across all stockists, providing a centralized view of company-wide inventory.
 *
 * Stores:
 * - Organization association
 * - Product association
 * - Batch association
 * - Available quantity
 * - Reserved quantity
 */

export const MasterInventoryTable = mysqlTable(
  "master_inventory",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    productId: char("product_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductsTable.id, {
        onDelete: "cascade",
      }),
    batchId: char("batch_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductBatchesTable.id, {
        onDelete: "restrict",
      }),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),
    reservedQuantity: decimal("reserved_quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),

    ...tableMetaData("MAIN"),
  },
  (table) => [
    uniqueIndex("master_inventory_batch_unique").on(
      table.organizationId,
      table.batchId,
    ),
  ],
);

export const MasterInventoryRelations = relations(
  MasterInventoryTable,
  ({ one }) => ({
    organization: one(OrganizationsTable, {
      fields: [MasterInventoryTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    product: one(ProductsTable, {
      fields: [MasterInventoryTable.productId],
      references: [ProductsTable.id],
    }),
    batch: one(ProductBatchesTable, {
      fields: [MasterInventoryTable.batchId],
      references: [ProductBatchesTable.id],
    }),
  }),
);

/**
 * InventoryMovementsTable
 *
 * Immutable-style transaction/history table for inventory changes.
 *
 * Instead of relying only on the current quantity in inventory tables,
 * this table records why and when inventory changed.
 *
 * Examples:
 * - Stock receipt
 * - Stock transfer
 * - Order allocation
 * - Sale
 * - Return
 * - Expiry
 * - Wastage
 * - Manual adjustment
 *
 * Stores:
 * - Organization
 * - Stockist (when applicable)
 * - Product and batch
 * - Movement type
 * - Quantity
 * - Reference entity
 * - Notes
 * - User responsible for the movement
 *
 * This table is important for inventory auditing and reconciliation.
 */

export const InventoryMovementsTable = mysqlTable(
  "inventory_movements",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    stockistId: char("stockist_id", {
      length: 10,
    }).references(() => StockistsTable.id, {
      onDelete: "set null",
    }),
    productId: char("product_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductsTable.id, {
        onDelete: "restrict",
      }),
    batchId: char("batch_id", {
      length: 10,
    })
      .notNull()
      .references(() => ProductBatchesTable.id, {
        onDelete: "restrict",
      }),
    type: inventoryMovementTypeEnum("type").notNull(),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    }).notNull(),
    referenceType: varchar("reference_type", {
      length: 50,
    }),
    referenceId: char("reference_id", {
      length: 10,
    }),
    notes: text("notes"),
    createdBy: char("created_by", {
      length: 10,
    }).references(() => UsersTable.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("INMV"),
  },
  (table) => [
    index("inventory_movements_stockist_idx").on(table.stockistId),
    index("inventory_movements_product_batch_idx").on(
      table.productId,
      table.batchId,
    ),
    index("inventory_movements_created_at_idx").on(table.createdAt),
  ],
);

export const InventoryMovementsRelations = relations(
  InventoryMovementsTable,
  ({ one }) => ({
    organization: one(OrganizationsTable, {
      fields: [InventoryMovementsTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    stockist: one(StockistsTable, {
      fields: [InventoryMovementsTable.stockistId],
      references: [StockistsTable.id],
    }),
    product: one(ProductsTable, {
      fields: [InventoryMovementsTable.productId],
      references: [ProductsTable.id],
    }),
    batch: one(ProductBatchesTable, {
      fields: [InventoryMovementsTable.batchId],
      references: [ProductBatchesTable.id],
    }),
    creator: one(UsersTable, {
      fields: [InventoryMovementsTable.createdBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * StockTransfersTable
 *
 * Represents stock transfer requests between stockists.
 *
 * Stores:
 * - Organization association
 * - From and to stockist
 * - Transfer status
 * - Requester and approver
 * - Approval timestamp
 * - Notes
 */

export const StockTransfersTable = mysqlTable("stock_transfers", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrganizationsTable.id, {
      onDelete: "cascade",
    }),
  fromStockistId: char("from_stockist_id", {
    length: 10,
  }).references(() => StockistsTable.id, {
    onDelete: "set null",
  }),
  toStockistId: char("to_stockist_id", {
    length: 10,
  }).references(() => StockistsTable.id, {
    onDelete: "set null",
  }),
  status: stockTransferStatusEnum("status").default("DRAFT").notNull(),
  requestedBy: char("requested_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  approvedBy: char("approved_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  approvedAt: timestamp("approved_at"),
  notes: text("notes"),

  ...tableMetaData("STTR"),
});

export const StockTransfersRelations = relations(
  StockTransfersTable,
  ({ one, many }) => ({
    organization: one(OrganizationsTable, {
      fields: [StockTransfersTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    fromStockist: one(StockistsTable, {
      fields: [StockTransfersTable.fromStockistId],
      references: [StockistsTable.id],
    }),
    toStockist: one(StockistsTable, {
      fields: [StockTransfersTable.toStockistId],
      references: [StockistsTable.id],
    }),
    requester: one(UsersTable, {
      fields: [StockTransfersTable.requestedBy],
      references: [UsersTable.id],
    }),
    approver: one(UsersTable, {
      fields: [StockTransfersTable.approvedBy],
      references: [UsersTable.id],
    }),
    items: many(StockTransferItemsTable),
  }),
);

/**
 * StockTransferItemsTable
 *
 * Represents the individual product/batch quantities included in a stock
 * transfer.
 *
 * One StockTransfersTable record can contain multiple transfer items.
 *
 * Stores:
 * - Transfer
 * - Product
 * - Batch
 * - Quantity
 *
 * Keeping transfer header and item information separate allows a single
 * transfer to contain multiple products and batches.
 */

export const StockTransferItemsTable = mysqlTable("stock_transfer_items", {
  id: autoGeneratedId(),
  transferId: char("transfer_id", {
    length: 10,
  })
    .notNull()
    .references(() => StockTransfersTable.id, {
      onDelete: "cascade",
    }),
  productId: char("product_id", {
    length: 10,
  })
    .notNull()
    .references(() => ProductsTable.id, {
      onDelete: "restrict",
    }),
  batchId: char("batch_id", {
    length: 10,
  })
    .notNull()
    .references(() => ProductBatchesTable.id, {
      onDelete: "restrict",
    }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),

  ...tableMetaData("STIT"),
});

export const StockTransferItemsRelations = relations(
  StockTransferItemsTable,
  ({ one }) => ({
    transfer: one(StockTransfersTable, {
      fields: [StockTransferItemsTable.transferId],
      references: [StockTransfersTable.id],
    }),
    product: one(ProductsTable, {
      fields: [StockTransferItemsTable.productId],
      references: [ProductsTable.id],
    }),
    batch: one(ProductBatchesTable, {
      fields: [StockTransferItemsTable.batchId],
      references: [ProductBatchesTable.id],
    }),
  }),
);

/**
 * FieldDaysTable
 *
 * Represents a field representative's working day in the field.
 *
 * This acts as the parent/anchor record for field activities performed
 * during a particular date.
 *
 * Stores:
 * - User and organization
 * - Work date
 * - Day status
 * - Travel mode
 * - Opening/closing odometer readings
 * - Odometer photographs
 * - Start/end selfies
 * - Start/end GPS coordinates
 * - Start/end timestamps
 * - Lock timestamp
 *
 * VisitsTable performed during the day are linked to this record.
 *
 * This table effectively provides the field-sales attendance/day lifecycle.
 */

export const FieldDaysTable = mysqlTable(
  "field_days",
  {
    id: autoGeneratedId(),
    userId: char("user_id", {
      length: 10,
    })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "cascade",
      }),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    workDate: date("work_date").notNull(),
    status: dayStatusEnum("status").default("OPEN").notNull(),
    travelMode: travelModeEnum("travel_mode"),
    openingOdometer: decimal("opening_odometer", {
      precision: 12,
      scale: 2,
    }),
    closingOdometer: decimal("closing_odometer", {
      precision: 12,
      scale: 2,
    }),
    openingOdometerPhotoId: char("opening_odometer_photo_id", {
      length: 10,
    }).references(() => MediaFilesTable.id, {
      onDelete: "set null",
    }),
    closingOdometerPhotoId: char("closing_odometer_photo_id", {
      length: 10,
    }).references(() => MediaFilesTable.id, {
      onDelete: "set null",
    }),
    startSelfieId: char("start_selfie_id", {
      length: 10,
    }).references(() => MediaFilesTable.id, {
      onDelete: "set null",
    }),
    endSelfieId: char("end_selfie_id", {
      length: 10,
    }).references(() => MediaFilesTable.id, {
      onDelete: "set null",
    }),
    startLatitude: decimal("start_latitude", {
      precision: 10,
      scale: 7,
    }),
    startLongitude: decimal("start_longitude", {
      precision: 10,
      scale: 7,
    }),
    endLatitude: decimal("end_latitude", {
      precision: 10,
      scale: 7,
    }),
    endLongitude: decimal("end_longitude", {
      precision: 10,
      scale: 7,
    }),
    startedAt: timestamp("started_at"),
    endedAt: timestamp("ended_at"),
    lockedAt: timestamp("locked_at"),

    ...tableMetaData("FLDY"),
  },
  (table) => [
    uniqueIndex("field_days_user_date_unique").on(table.userId, table.workDate),
    index("field_days_user_date_idx").on(table.userId, table.workDate),
  ],
);

export const FieldDaysRelations = relations(
  FieldDaysTable,
  ({ one, many }) => ({
    user: one(UsersTable, {
      fields: [FieldDaysTable.userId],
      references: [UsersTable.id],
    }),
    organization: one(OrganizationsTable, {
      fields: [FieldDaysTable.organizationId],
      references: [OrganizationsTable.id],
    }),
    openingOdometerPhoto: one(MediaFilesTable, {
      fields: [FieldDaysTable.openingOdometerPhotoId],
      references: [MediaFilesTable.id],
    }),
    closingOdometerPhoto: one(MediaFilesTable, {
      fields: [FieldDaysTable.closingOdometerPhotoId],
      references: [MediaFilesTable.id],
    }),
    startSelfie: one(MediaFilesTable, {
      fields: [FieldDaysTable.startSelfieId],
      references: [MediaFilesTable.id],
    }),
    endSelfie: one(MediaFilesTable, {
      fields: [FieldDaysTable.endSelfieId],
      references: [MediaFilesTable.id],
    }),
    unlockRequests: many(DayUnlockRequestsTable),
    visits: many(VisitsTable),
  }),
);

/**
 * DayUnlockRequestsTable
 *
 * Represents a request to reopen or unlock a previously locked field day.
 *
 * Field days may be locked after completion to prevent unauthorized changes.
 * If a correction is required, the user can submit an unlock request.
 *
 * Stores:
 * - Field day
 * - Requesting user
 * - Reason
 * - Approval status
 * - Reviewer
 * - Review comment
 * - Review timestamp
 *
 * Provides an auditable approval workflow for modifying completed days.
 */

export const DayUnlockRequestsTable = mysqlTable("day_unlock_requests", {
  id: autoGeneratedId(),
  fieldDayId: char("field_day_id", {
    length: 10,
  })
    .notNull()
    .references(() => FieldDaysTable.id, {
      onDelete: "cascade",
    }),
  requestedBy: char("requested_by", {
    length: 10,
  })
    .notNull()
    .references(() => UsersTable.id, {
      onDelete: "restrict",
    }),
  reviewedBy: char("reviewed_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  reason: text("reason").notNull(),
  status: approvalStatusEnum("status").default("PENDING").notNull(),
  reviewComment: text("review_comment"),
  reviewedAt: timestamp("reviewed_at"),

  ...tableMetaData("DURQ"),
});

export const DayUnlockRequestsRelations = relations(
  DayUnlockRequestsTable,
  ({ one }) => ({
    fieldDay: one(FieldDaysTable, {
      fields: [DayUnlockRequestsTable.fieldDayId],
      references: [FieldDaysTable.id],
    }),
    requester: one(UsersTable, {
      fields: [DayUnlockRequestsTable.requestedBy],
      references: [UsersTable.id],
    }),
    reviewer: one(UsersTable, {
      fields: [DayUnlockRequestsTable.reviewedBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * VisitsTable
 *
 * Represents a visit made by a field representative to a customer location.
 *
 * Each visit is associated with a specific field day and user.
 *
 * Stores:
 * - Field day
 * - User
 * - Customer
 * - Route
 * - Check-in and check-out timestamps
 * - GPS coordinates
 * - Visit photo
 * - Outcome and feedback
 *
 * Provides a detailed record of field activities and customer interactions.
 */

export const VisitsTable = mysqlTable(
  "visits",
  {
    id: autoGeneratedId(),
    fieldDayId: char("field_day_id", {
      length: 10,
    })
      .notNull()
      .references(() => FieldDaysTable.id, {
        onDelete: "cascade",
      }),
    userId: char("user_id", {
      length: 10,
    })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "cascade",
      }),
    customerId: char("customer_id", {
      length: 10,
    })
      .notNull()
      .references(() => CustomersTable.id, {
        onDelete: "restrict",
      }),
    routeId: char("route_id", {
      length: 10,
    }).references(() => RoutesTable.id, {
      onDelete: "set null",
    }),
    checkInAt: timestamp("check_in_at").notNull(),
    checkOutAt: timestamp("check_out_at"),
    checkInLatitude: decimal("check_in_latitude", {
      precision: 10,
      scale: 7,
    }).notNull(),
    checkInLongitude: decimal("check_in_longitude", {
      precision: 10,
      scale: 7,
    }).notNull(),
    checkOutLatitude: decimal("check_out_latitude", {
      precision: 10,
      scale: 7,
    }),
    checkOutLongitude: decimal("check_out_longitude", {
      precision: 10,
      scale: 7,
    }),
    accuracyMeters: decimal("accuracy_meters", {
      precision: 10,
      scale: 2,
    }),
    visitPhotoId: char("visit_photo_id", {
      length: 10,
    }).references(() => MediaFilesTable.id, {
      onDelete: "set null",
    }),
    outcome: visitOutcomeEnum("outcome"),
    feedback: text("feedback"),
    remarks: text("remarks"),
    durationSeconds: int("duration_seconds"),

    ...tableMetaData("VIST"),
  },
  (table) => [
    index("visits_user_date_idx").on(table.userId, table.checkInAt),
    index("visits_customer_idx").on(table.customerId),
    index("visits_geo_idx").on(table.checkInLatitude, table.checkInLongitude),
  ],
);

export const VisitsRelations = relations(VisitsTable, ({ one, many }) => ({
  fieldDay: one(FieldDaysTable, {
    fields: [VisitsTable.fieldDayId],
    references: [FieldDaysTable.id],
  }),
  user: one(UsersTable, {
    fields: [VisitsTable.userId],
    references: [UsersTable.id],
  }),
  customer: one(CustomersTable, {
    fields: [VisitsTable.customerId],
    references: [CustomersTable.id],
  }),
  route: one(RoutesTable, {
    fields: [VisitsTable.routeId],
    references: [RoutesTable.id],
  }),
  photo: one(MediaFilesTable, {
    fields: [VisitsTable.visitPhotoId],
    references: [MediaFilesTable.id],
  }),
  orders: many(OrdersTable),
  followUps: many(CustomerFollowUpsTable),
}));

/**
 * OrdersTable
 *
 * Represents a customer order generated through the field-sales process.
 *
 * An order connects the customer, field representative, stockist, route,
 * and optionally the visit from which the order originated.
 *
 * Stores:
 * - Order number
 * - Customer and user
 * - Stockist responsible for fulfillment
 * - Route and originating visit
 * - Order type
 * - Order status
 * - Payment status
 * - Financial totals
 * - Notes
 * - Submission timestamp
 *
 * Individual products in the order are stored in OrderItemsTable.
 */

export const OrdersTable = mysqlTable(
  "orders",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    orderNumber: varchar("order_number", {
      length: 50,
    }).notNull(),
    userId: char("user_id", {
      length: 10,
    })
      .notNull()
      .references(() => UsersTable.id, {
        onDelete: "restrict",
      }),
    customerId: char("customer_id", {
      length: 10,
    })
      .notNull()
      .references(() => CustomersTable.id, {
        onDelete: "restrict",
      }),
    stockistId: char("stockist_id", {
      length: 10,
    })
      .notNull()
      .references(() => StockistsTable.id, {
        onDelete: "restrict",
      }),
    routeId: char("route_id", {
      length: 10,
    }).references(() => RoutesTable.id, {
      onDelete: "set null",
    }),
    visitId: char("visit_id", {
      length: 10,
    }).references(() => VisitsTable.id, {
      onDelete: "set null",
    }),
    orderType: orderTypeEnum("order_type").notNull(),
    status: orderStatusEnum("status").default("DRAFT").notNull(),
    paymentStatus: paymentStatusEnum("payment_status")
      .default("PENDING")
      .notNull(),
    subtotal: decimal("subtotal", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    discountAmount: decimal("discount_amount", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    taxAmount: decimal("tax_amount", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    grandTotal: decimal("grand_total", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    notes: text("notes"),
    submittedAt: timestamp("submitted_at"),

    ...tableMetaData("ORDR"),
  },
  (table) => [
    uniqueIndex("orders_org_number_unique").on(
      table.organizationId,
      table.orderNumber,
    ),
    index("orders_user_idx").on(table.userId),
    index("orders_customer_idx").on(table.customerId),
    index("orders_stockist_idx").on(table.stockistId),
    index("orders_status_idx").on(table.status),
  ],
);

export const OrdersRelations = relations(OrdersTable, ({ one, many }) => ({
  organization: one(OrganizationsTable, {
    fields: [OrdersTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  user: one(UsersTable, {
    fields: [OrdersTable.userId],
    references: [UsersTable.id],
  }),
  customer: one(CustomersTable, {
    fields: [OrdersTable.customerId],
    references: [CustomersTable.id],
  }),
  stockist: one(StockistsTable, {
    fields: [OrdersTable.stockistId],
    references: [StockistsTable.id],
  }),
  route: one(RoutesTable, {
    fields: [OrdersTable.routeId],
    references: [RoutesTable.id],
  }),
  visit: one(VisitsTable, {
    fields: [OrdersTable.visitId],
    references: [VisitsTable.id],
  }),
  items: many(OrderItemsTable),
  fulfillments: many(OrderFulfillmentsTable),
  statusHistory: many(OrderStatusHistoryTable),
  payments: many(PaymentsTable),
}));

/**
 * OrderItemsTable
 *
 * Represents an individual product line within an order.
 *
 * One order can contain multiple order items.
 *
 * Stores:
 * - Order
 * - Product
 * - Optional batch
 * - Quantity
 * - Unit price
 * - Discount information
 * - Tax information
 * - Final line total
 *
 * Keeping items separate from OrdersTable allows flexible multi-product orders.
 */

export const OrderItemsTable = mysqlTable("order_items", {
  id: autoGeneratedId(),
  orderId: char("order_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrdersTable.id, {
      onDelete: "cascade",
    }),
  productId: char("product_id", {
    length: 10,
  })
    .notNull()
    .references(() => ProductsTable.id, {
      onDelete: "restrict",
    }),
  batchId: char("batch_id", {
    length: 10,
  }).references(() => ProductBatchesTable.id, {
    onDelete: "restrict",
  }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),
  unitPrice: decimal("unit_price", {
    precision: 14,
    scale: 2,
  }).notNull(),
  discountPercent: decimal("discount_percent", {
    precision: 6,
    scale: 2,
  })
    .default("0")
    .notNull(),
  discountAmount: decimal("discount_amount", {
    precision: 14,
    scale: 2,
  })
    .default("0")
    .notNull(),
  taxPercent: decimal("tax_percent", {
    precision: 6,
    scale: 2,
  })
    .default("0")
    .notNull(),
  taxAmount: decimal("tax_amount", {
    precision: 14,
    scale: 2,
  })
    .default("0")
    .notNull(),
  lineTotal: decimal("line_total", {
    precision: 14,
    scale: 2,
  }).notNull(),

  ...tableMetaData("ORIT"),
});

export const OrderItemsRelations = relations(OrderItemsTable, ({ one }) => ({
  order: one(OrdersTable, {
    fields: [OrderItemsTable.orderId],
    references: [OrdersTable.id],
  }),
  product: one(ProductsTable, {
    fields: [OrderItemsTable.productId],
    references: [ProductsTable.id],
  }),
  batch: one(ProductBatchesTable, {
    fields: [OrderItemsTable.batchId],
    references: [ProductBatchesTable.id],
  }),
}));

/**
 * OrderFulfillmentsTable
 *
 * Represents the fulfillment status of an order.
 *
 * Each order can have one or more fulfillment records.
 *
 * Stores:
 * - Order
 * - Status
 * - Invoice information
 * - Dispatch and delivery timestamps
 * - Delivery confirmation details
 *
 * Provides a way to track the progress of order fulfillment.
 */

export const OrderFulfillmentsTable = mysqlTable("order_fulfillments", {
  id: autoGeneratedId(),
  orderId: char("order_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrdersTable.id, {
      onDelete: "cascade",
    }),
  status: fulfillmentStatusEnum("status").default("PENDING").notNull(),
  invoiceNumber: varchar("invoice_number", {
    length: 100,
  }),
  invoiceDate: date("invoice_date"),
  invoiceUrl: text("invoice_url"),
  dispatchedAt: timestamp("dispatched_at"),
  deliveredAt: timestamp("delivered_at"),
  deliveryConfirmedBy: char("delivery_confirmed_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  deliveryRemarks: text("delivery_remarks"),

  ...tableMetaData("ORFL"),
});

export const OrderFulfillmentsRelations = relations(
  OrderFulfillmentsTable,
  ({ one }) => ({
    order: one(OrdersTable, {
      fields: [OrderFulfillmentsTable.orderId],
      references: [OrdersTable.id],
    }),
    deliveryConfirmer: one(UsersTable, {
      fields: [OrderFulfillmentsTable.deliveryConfirmedBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * OrderStatusHistoryTable
 *
 * Provides an audit trail of order status changes.
 *
 * Instead of storing only the current status in OrdersTable, this table records
 * how the order moved through its lifecycle.
 *
 * Example:
 *   DRAFT → SUBMITTED → CONFIRMED → DISPATCHED → DELIVERED
 *
 * Stores:
 * - Order
 * - Previous status
 * - New status
 * - User who changed the status
 * - Comment
 *
 * Useful for auditing, troubleshooting, reporting, and workflow history.
 */

export const OrderStatusHistoryTable = mysqlTable("order_status_history", {
  id: autoGeneratedId(),
  orderId: char("order_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrdersTable.id, {
      onDelete: "cascade",
    }),
  oldStatus: orderStatusEnum("old_status"),
  newStatus: orderStatusEnum("new_status").notNull(),
  changedBy: char("changed_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  comment: text("comment"),

  ...tableMetaData("ORSH"),
});

export const OrderStatusHistoryRelations = relations(
  OrderStatusHistoryTable,
  ({ one }) => ({
    order: one(OrdersTable, {
      fields: [OrderStatusHistoryTable.orderId],
      references: [OrdersTable.id],
    }),
    changedByUser: one(UsersTable, {
      fields: [OrderStatusHistoryTable.changedBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * PaymentsTable
 *
 * Represents a payment transaction made by a customer.
 *
 * Each payment is associated with an order and a customer.
 *
 * Stores:
 * - Order
 * - Customer
 * - Payment method
 * - Amount
 * - Status
 * - Transaction reference
 * - Collection timestamp
 * - Remarks
 *
 * Provides a detailed record of payment activities.
 */

export const PaymentsTable = mysqlTable("payments", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", {
    length: 10,
  })
    .notNull()
    .references(() => OrganizationsTable.id, {
      onDelete: "cascade",
    }),
  orderId: char("order_id", {
    length: 10,
  }).references(() => OrdersTable.id, {
    onDelete: "set null",
  }),
  customerId: char("customer_id", {
    length: 10,
  })
    .notNull()
    .references(() => CustomersTable.id, {
      onDelete: "restrict",
    }),
  collectedBy: char("collected_by", {
    length: 10,
  })
    .notNull()
    .references(() => UsersTable.id, {
      onDelete: "restrict",
    }),
  amount: decimal("amount", {
    precision: 14,
    scale: 2,
  }).notNull(),
  method: paymentMethodEnum("method").notNull(),
  status: paymentStatusEnum("status").default("PAID").notNull(),
  transactionReference: varchar("transaction_reference", { length: 150 }),
  collectedAt: timestamp("collected_at").defaultNow().notNull(),
  remarks: text("remarks"),

  ...tableMetaData("PYMT"),
});

export const PaymentsRelations = relations(PaymentsTable, ({ one }) => ({
  organization: one(OrganizationsTable, {
    fields: [PaymentsTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  order: one(OrdersTable, {
    fields: [PaymentsTable.orderId],
    references: [OrdersTable.id],
  }),
  customer: one(CustomersTable, {
    fields: [PaymentsTable.customerId],
    references: [CustomersTable.id],
  }),
  collector: one(UsersTable, {
    fields: [PaymentsTable.collectedBy],
    references: [UsersTable.id],
  }),
}));

/**
 * CollectionHandoversTable
 *
 * Represents the process of handing collected money from a field user to
 * the responsible stockist or organization representative.
 *
 * This provides accountability between:
 *   Field collection → Physical/financial handover → Verification
 *
 * Stores:
 * - User who collected the money
 * - Stockist receiving the money
 * - Amount
 * - Handover status
 * - Handover timestamp
 * - Verifying user
 * - Verification timestamp
 * - Remarks
 *
 * Useful for cash/collection reconciliation and financial accountability.
 */
export const CollectionHandoversTable = mysqlTable("collection_handovers", {
  id: autoGeneratedId(),
  userId: char("user_id", {
    length: 10,
  })
    .notNull()
    .references(() => UsersTable.id, {
      onDelete: "restrict",
    }),
  stockistId: char("stockist_id", {
    length: 10,
  })
    .notNull()
    .references(() => StockistsTable.id, {
      onDelete: "restrict",
    }),
  amount: decimal("amount", {
    precision: 14,
    scale: 2,
  }).notNull(),
  status: collectionStatusEnum("status").default("PENDING").notNull(),
  handedOverAt: timestamp("handed_over_at"),
  verifiedBy: char("verified_by", {
    length: 10,
  }).references(() => UsersTable.id, {
    onDelete: "set null",
  }),
  verifiedAt: timestamp("verified_at"),
  remarks: text("remarks"),

  ...tableMetaData("COHO"),
});

export const CollectionHandoversRelations = relations(
  CollectionHandoversTable,
  ({ one }) => ({
    user: one(UsersTable, {
      fields: [CollectionHandoversTable.userId],
      references: [UsersTable.id],
    }),
    stockist: one(StockistsTable, {
      fields: [CollectionHandoversTable.stockistId],
      references: [StockistsTable.id],
    }),
    verifier: one(UsersTable, {
      fields: [CollectionHandoversTable.verifiedBy],
      references: [UsersTable.id],
    }),
  }),
);

/**
 * ExpiryWastageEntriesTable
 *
 * Represents entries for expired or wasted products.
 *
 * Stores:
 * - Stockist
 * - Product
 * - Batch
 * - Quantity
 * - Reason for expiry/wastage
 * - Remarks
 * - User who entered the entry
 *
 * Useful for inventory management and financial reporting.
 */

export const ExpiryWastageEntriesTable = mysqlTable("expiry_wastage_entries", {
  id: autoGeneratedId(),

  stockistId: char("stockist_id", {
    length: 10,
  }).references(() => StockistsTable.id, {
    onDelete: "set null",
  }),
  productId: char("product_id", {
    length: 10,
  })
    .notNull()
    .references(() => ProductsTable.id, {
      onDelete: "restrict",
    }),
  batchId: char("batch_id", {
    length: 10,
  })
    .notNull()
    .references(() => ProductBatchesTable.id, {
      onDelete: "restrict",
    }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),
  reason: varchar("reason", {
    length: 150,
  }).notNull(),
  remarks: text("remarks"),
  enteredBy: char("entered_by", {
    length: 10,
  })
    .notNull()
    .references(() => UsersTable.id, {
      onDelete: "restrict",
    }),

  ...tableMetaData("EXWS"),
});

export const ExpiryWastageEntriesRelations = relations(
  ExpiryWastageEntriesTable,
  ({ one }) => ({
    stockist: one(StockistsTable, {
      fields: [ExpiryWastageEntriesTable.stockistId],
      references: [StockistsTable.id],
    }),
    product: one(ProductsTable, {
      fields: [ExpiryWastageEntriesTable.productId],
      references: [ProductsTable.id],
    }),
    batch: one(ProductBatchesTable, {
      fields: [ExpiryWastageEntriesTable.batchId],
      references: [ProductBatchesTable.id],
    }),
    enterer: one(UsersTable, {
      fields: [ExpiryWastageEntriesTable.enteredBy],
      references: [UsersTable.id],
    }),
  }),
);
/**
 * CustomerFollowUpsTable
 *
 * Represents a future action/task associated with a customer.
 *
 * Follow-ups can be created during or after a customer visit and assigned
 * to a specific field representative.
 *
 * Examples:
 * - Call doctor next week
 * - Follow up on product interest
 * - Collect pending payment
 * - Revisit customer
 * - Submit requested information
 *
 * Stores:
 * - Customer
 * - Assigned user
 * - Related visit (optional)
 * - Due date
 * - Notes
 * - Completion timestamp
 *
 * A null completedAt means the follow-up is still pending.
 */

export const CustomerFollowUpsTable = mysqlTable("customer_follow_ups", {
  id: autoGeneratedId(),

  customerId: char("customer_id", {
    length: 10,
  })
    .notNull()
    .references(() => CustomersTable.id, {
      onDelete: "cascade",
    }),

  assignedTo: char("assigned_to", {
    length: 10,
  })
    .notNull()
    .references(() => UsersTable.id, {
      onDelete: "restrict",
    }),

  visitId: char("visit_id", {
    length: 10,
  }).references(() => VisitsTable.id, {
    onDelete: "set null",
  }),
  dueDate: date("due_date").notNull(),
  notes: text("notes"),
  completedAt: timestamp("completed_at"),

  ...tableMetaData("CUFU"),
});

export const CustomerFollowUpsRelations = relations(
  CustomerFollowUpsTable,
  ({ one }) => ({
    customer: one(CustomersTable, {
      fields: [CustomerFollowUpsTable.customerId],
      references: [CustomersTable.id],
    }),
    assignee: one(UsersTable, {
      fields: [CustomerFollowUpsTable.assignedTo],
      references: [UsersTable.id],
    }),
    visit: one(VisitsTable, {
      fields: [CustomerFollowUpsTable.visitId],
      references: [VisitsTable.id],
    }),
  }),
);

/**
 * AuditLogsTable
 *
 * Represents a log of all audit events in the system.
 *
 * Stores:
 * - Organization
 * - User
 * - Action taken
 * - Entity type and ID
 * - Old and new values
 * - IP address
 * - User agent
 *
 * Useful for compliance, troubleshooting, and historical analysis.
 */

export const AuditLogsTable = mysqlTable(
  "audit_logs",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    userId: char("user_id", {
      length: 10,
    }).references(() => UsersTable.id, {
      onDelete: "set null",
    }),
    action: varchar("action", {
      length: 100,
    }).notNull(),
    entityType: varchar("entity_type", {
      length: 100,
    }).notNull(),
    entityId: char("entity_id", {
      length: 10,
    }),
    oldValues: json("old_values"),
    newValues: json("new_values"),
    ipAddress: varchar("ip_address", {
      length: 100,
    }),
    userAgent: text("user_agent"),

    ...tableMetaData("AUDL"),
  },
  (table) => [
    index("audit_logs_entity_idx").on(table.entityType, table.entityId),
    index("audit_logs_user_idx").on(table.userId),
    index("audit_logs_created_at_idx").on(table.createdAt),
  ],
);

export const AuditLogsRelations = relations(AuditLogsTable, ({ one }) => ({
  organization: one(OrganizationsTable, {
    fields: [AuditLogsTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  user: one(UsersTable, {
    fields: [AuditLogsTable.userId],
    references: [UsersTable.id],
  }),
}));

/**
 * OrganizationSettingsTable
 *
 * Stores configurable key-value settings for an organization.
 *
 * This avoids adding a new database column every time a configurable
 * organization-level option is introduced.
 *
 * Examples:
 * - Default payment terms
 * - Order configuration
 * - Visit radius
 * - Feature flags
 * - Notification settings
 * - Business preferences
 *
 * The value is stored as JSON so settings can represent strings, numbers,
 * booleans, arrays, or structured objects.
 *
 * Each organization can have only one value for a given setting key.
 */

export const OrganizationSettingsTable = mysqlTable(
  "organization_settings",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => OrganizationsTable.id, {
        onDelete: "cascade",
      }),
    key: varchar("key", {
      length: 100,
    }).notNull(),
    value: json("value"),

    ...tableMetaData("ORST"),
  },
  (table) => [
    uniqueIndex("organization_settings_key_unique").on(
      table.organizationId,
      table.key,
    ),
  ],
);

export const OrganizationSettingsRelations = relations(
  OrganizationSettingsTable,
  ({ one }) => ({
    organization: one(OrganizationsTable, {
      fields: [OrganizationSettingsTable.organizationId],
      references: [OrganizationsTable.id],
    }),
  }),
);

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
type TableIdentifierToken =
  /**
   * OrganizationsTable
   */
  | "ORGN"
  /**
   * UsersTable
   */
  | "USER"
  /**
   * MediaFilesTable
   */
  | "MDFL"
  /**
   * TerritoriesTable
   */
  | "TRTS"
  /**
   * RoutesTable
   */
  | "ROUT"
  /**
   * UserTerritoriesTable
   */
  | "USTE"
  /**
   * UserRoutesTable
   */
  | "USRT"
  /**
   * RouteStopsTable
   */
  | "RUST"
  /**
   * StockistsTable
   */
  | "STKT"
  /**
   * UserStockistsTable
   */
  | "USSK"
  /**
   * CustomersTable
   */
  | "CUST"
  /**
   * CustomerAssignmentsTable
   */
  | "CUAS"
  /**
   * DoctorProfilesTable
   */
  | "DOCS"
  /**
   * DoctorAvailabilityTable
   */
  | "DOAV"
  /**
   * ProductCategoriesTable
   */
  | "PRCT"
  /**
   * ProductsTable
   */
  | "PROD"
  /**
   * ProductMediaTable
   */
  | "PRMD"
  /**
   * DoctorProductPreferencesTable
   */
  | "DPPR"
  /**
   * ProductPricesTable
   */
  | "PRPR"
  /**
   * ProductBatchesTable
   */
  | "PRBT"
  /**
   * StockistInventoryTable
   */
  | "SKIV"
  /**
   * MasterInventoryTable
   */
  | "MAIN"
  /**
   * InventoryMovementsTable
   */
  | "INMV"
  /**
   * StockTransfersTable
   */
  | "STTR"
  /**
   * StockTransferItemsTable
   */
  | "STIT"
  /**
   * FieldDaysTable
   */
  | "FLDY"
  /**
   * DayUnlockRequestsTable
   */
  | "DURQ"
  /**
   * VisitsTable
   */
  | "VIST"
  /**
   * OrdersTable
   */
  | "ORDR"
  /**
   * OrderItemsTable
   */
  | "ORIT"
  /**
   * OrderFulfillmentsTable
   */
  | "ORFL"
  /**
   * OrderStatusHistoryTable
   */
  | "ORSH"
  /**
   * PaymentsTable
   */
  | "PYMT"
  /**
   * CollectionHandoversTable
   */
  | "COHO"
  /**
   * ExpiryWastageEntriesTable
   */
  | "EXWS"
  /**
   * CustomerFollowUpsTable
   */
  | "CUFU"
  /**
   * AuditLogsTable
   */
  | "AUDL"
  /**
   * OrganizationSettingsTable
   */
  | "ORST";

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

// function autoIncrementedId() {
//   return int("id").primaryKey().autoincrement();
// };
function autoGeneratedId() {
  return char("id", { length: 10 })
    .primaryKey()
    .$defaultFn(() => id());
}
function tableMetaData(tableIdentifierToken: TableIdentifierToken) {
  return {
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .onUpdateNow()
      .notNull()
      .$onUpdateFn(() => new Date(Date.now())),
    tableIdentifierToken: char("table_identifier_token", {
      length: 4,
    }).$defaultFn(() => tableIdentifierToken),
  };
}

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
const tableMapper: Record<TableIdentifierToken, string> = {
  ORGN: "organizations",
  USER: "users",
  MDFL: "media_files",
  TRTS: "territories",
  ROUT: "routes",
  USTE: "user_territories",
  USRT: "user_routes",
  RUST: "route_stops",
  STKT: "stockists",
  USSK: "user_stockists",
  CUST: "customers",
  CUAS: "customer_assignments",
  DOCS: "doctor_profiles",
  DOAV: "doctor_availability",
  PRCT: "product_categories",
  PROD: "products",
  PRMD: "product_media",
  DPPR: "doctor_product_preferences",
  PRPR: "product_prices",
  PRBT: "product_batches",
  SKIV: "stockist_inventory",
  MAIN: "master_inventory",
  INMV: "inventory_movements",
  STTR: "stock_transfers",
  STIT: "stock_transfer_items",
  FLDY: "field_days",
  DURQ: "day_unlock_requests",
  VIST: "visits",
  ORDR: "orders",
  ORIT: "order_items",
  ORFL: "order_fulfillments",
  ORSH: "order_status_history",
  PYMT: "payments",
  COHO: "collection_handovers",
  EXWS: "expiry_wastage_entries",
  CUFU: "customer_follow_ups",
  AUDL: "audit_logs",
  ORST: "organization_settings",
} as const;

export function identifyTable(
  tableIdentifierToken: TableIdentifierToken,
): string {
  const tableName = tableMapper[tableIdentifierToken];

  if (!tableName) {
    throw new Error("Provide a valid prefix to identify table name.");
  }

  return tableName;
}
