import {
  boolean,
  char,
  date,
  decimal,
  index,
  int,
  json,
  mysqlTable,
  primaryKey,
  text,
  time,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";
import {
  approvalStatusEnum,
  batchStatusEnum,
  collectionStatusEnum,
  customerTypeEnum,
  dayStatusEnum,
  fulfillmentStatusEnum,
  inventoryMovementTypeEnum,
  orderStatusEnum,
  orderTypeEnum,
  paymentMethodEnum,
  paymentStatusEnum,
  routeOwnershipEnum,
  stockTransferStatusEnum,
  travelModeEnum,
  userRoleEnum,
  userStatusEnum,
  visitOutcomeEnum,
} from "./enums";
import { relations } from "drizzle-orm";

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
export type TableIdentifierToken =
  /**
   * Organizations
   */
  | "ORGN"
  /**
   * Users
   */
  | "USER"
  /**
   * MediaFiles
   */
  | "MDFL"
  /**
   * Territories
   */
  | "TRTS"
  /**
   * Routes
   */
  | "ROUT"
  /**
   * UserTerritories
   */
  | "USTE"
  /**
   * UserRoutes
   */
  | "USRT"
  /**
   * RouteStops
   */
  | "RUST"
  /**
   * Stockists
   */
  | "STKT"
  /**
   * UserStockists
   */
  | "USSK"
  /**
   * Customers
   */
  | "CUST"
  /**
   * CustomerAssignments
   */
  | "CUAS"
  /**
   * DoctorProfiles
   */
  | "DOCS"
  /**
   * DoctorAvailability
   */
  | "DOAV"
  /**
   * ProductCategories
   */
  | "PRCT"
  /**
   * Products
   */
  | "PROD"
  /**
   * ProductMedia
   */
  | "PRMD"
  /**
   * DoctorProductPreferences
   */
  | "DPPR"
  /**
   * ProductPrices
   */
  | "PRPR"
  /**
   * ProductBatches
   */
  | "PRBT"
  /**
   * StockistInventory
   */
  | "SKIV"
  /**
   * MasterInventory
   */
  | "MAIN"
  /**
   * InventoryMovements
   */
  | "INMV"
  /**
   * StockTransfers
   */
  | "STTR"
  /**
   * StockTransferItems
   */
  | "STIT"
  /**
   * FieldDays
   */
  | "FLDY"
  /**
   * DayUnlockRequests
   */
  | "DURQ"
  /**
   * Visits
   */
  | "VIST"
  /**
   * Orders
   */
  | "ORDR"
  /**
   * OrderItems
   */
  | "ORIT"
  /**
   * OrderFulfillments
   */
  | "ORFL"
  /**
   * OrderStatusHistory
   */
  | "ORSH"
  /**
   * Payments
   */
  | "PYMT"
  /**
   * CollectionHandovers
   */
  | "COHO"
  /**
   * ExpiryWastageEntries
   */
  | "EXWS"
  /**
   * CustomerFollowUps
   */
  | "CUFU"
  /**
   * AuditLogs
   */
  | "AUDL"
  /**
   * OrganizationSettings
   */
  | "ORST";

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

// const autoIncrementedId = () => {
//   return int("id").primaryKey().autoincrement();
// };
const autoGeneratedId = () => {
  return char("id", { length: 10 })
    .primaryKey()
    .$defaultFn(() => "");
};
const tableMetaData = (tableIdentifierToken: TableIdentifierToken) => {
  return {
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").onUpdateNow().notNull(),
    tableIdentifierToken: char("table_identifier_token", {
      length: 4,
    }).$defaultFn(() => tableIdentifierToken),
  };
};

// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------
// --------------------------------------------------------------------------------

/**
 * This is used to identify which table the data is from,
 * and if there is any querry we have to do we can understand
 * in which table we have to do the query.
 */
const tableMapper: Record<TableIdentifierToken, string> = {
  ORGN: "organizations",
  USER: "users",
  MDFL: "media_files",
  TRTS: "territories",
  ROUT: "routes",
  USTE: "user_territories",
  USRT: "user_routes",
  RUST: "route_stops",
  STKT: "stockists",
  USSK: "user_stockists",
  CUST: "customers",
  CUAS: "customer_assignments",
  DOCS: "doctor_profiles",
  DOAV: "doctor_availability",
  PRCT: "product_categories",
  PROD: "products",
  PRMD: "product_media",
  DPPR: "doctor_product_preferences",
  PRPR: "product_prices",
  PRBT: "product_batches",
  SKIV: "stockist_inventory",
  MAIN: "master_inventory",
  INMV: "inventory_movements",
  STTR: "stock_transfers",
  STIT: "stock_transfer_items",
  FLDY: "field_days",
  DURQ: "day_unlock_requests",
  VIST: "visits",
  ORDR: "orders",
  ORIT: "order_items",
  ORFL: "order_fulfillments",
  ORSH: "order_status_history",
  PYMT: "payments",
  COHO: "collection_handovers",
  EXWS: "expiry_wastage_entries",
  CUFU: "customer_follow_ups",
  AUDL: "audit_logs",
  ORST: "organization_settings",
} as const;

export function identifyTable(
  tableIdentifierToken: TableIdentifierToken,
): string {
  const tableName = tableMapper[tableIdentifierToken];

  if (!tableName) {
    throw new Error("Provide a valid prefix to identify table name.");
  }

  return tableName;
}

/* =========================================================
  ORGANIZATION
========================================================= */

export const Organizations = mysqlTable(
  "organizations",
  {
    id: autoGeneratedId(),
    name: varchar("name", { length: 255 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    email: varchar("email", { length: 255 }).unique(),
    phone: varchar("phone", { length: 30 }),
    address: text("address"),
    pinCode: char("pin_code", { length: 6 }),
    gstin: varchar("gstin", { length: 20 }),
    pan: varchar("pan", { length: 20 }),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("ORGN"),
  },
  (table) => [uniqueIndex("organizations_code_unique").on(table.code)],
);

export const OrganizationRelations = relations(Organizations, ({ many }) => ({
  associatedUsers: many(Users),
  mediaFiles: many(MediaFiles),
  assignedTerritories: many(Territories),
  assignedRoutes: many(Routes),
}));

/* =========================================================
  USERS
========================================================= */

export const Users = mysqlTable(
  "users",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", { length: 10 }),
    role: userRoleEnum("role").notNull(),
    name: varchar("name", { length: 150 }).notNull(),
    email: varchar("email", { length: 255 }).notNull(),
    phone: varchar("phone", { length: 30 }).notNull(),
    passwordHash: text("password_hash"),
    employeeCode: varchar("employee_code", { length: 50 }),
    status: userStatusEnum("status").default("UNDER_VERIFICATION").notNull(),
    avatarUrl: text("avatar_url"),
    lastLoginAt: timestamp("last_login_at"),

    ...tableMetaData("USER"),
  },
  (table) => [
    index("users_employee_code_idx").on(
      table.organizationId,
      table.employeeCode,
    ),
  ],
);

export const UserRelations = relations(Users, ({ many }) => ({
  associatedOrganizations: many(Organizations),
  mediaFiles: many(MediaFiles),
}));

/* =========================================================
  MEDIA / FILES
========================================================= */

export const MediaFiles = mysqlTable("media_files", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", { length: 10 })
    .notNull()
    .references(() => Organizations.id, {
      onUpdate: "cascade",
      onDelete: "cascade",
    }),
  uploadedBy: char("uploaded_by", { length: 10 }).references(() => Users.id, {
    onUpdate: "cascade",
    onDelete: "set null",
  }),
  url: text("url").notNull(),
  fileName: varchar("file_name", { length: 255 }),
  mimeType: varchar("mime_type", { length: 100 }),
  fileSize: int("file_size"),
  width: int("width"),
  height: int("height"),
  metadata: json("metadata"),

  ...tableMetaData("MDFL"),
});

export const MediaFilesRelations = relations(MediaFiles, ({ one }) => ({
  associatedOrganization: one(Organizations, {
    fields: [MediaFiles.organizationId],
    references: [Organizations.id],
  }),
  uploaderUser: one(Users),
}));

/* =========================================================
  TERRITORIES
========================================================= */

export const Territories = mysqlTable(
  "territories",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", { length: 10 })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    name: varchar("name", { length: 150 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    state: varchar("state", { length: 100 }),
    district: varchar("district", { length: 100 }),
    city: varchar("city", { length: 100 }),
    pinCode: varchar("pin_code", { length: 10 }),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("TRTS"),
  },
  (table) => [
    uniqueIndex("territories_org_code_unique").on(
      table.organizationId,
      table.code,
    ),
  ],
);

export const TerritoriesRelations = relations(Territories, ({ many }) => ({
  associatedOrganizations: many(Organizations),
  route: many(Routes),
  associatedUsers: many(Users),
}));

/* =========================================================
  ROUTES
========================================================= */

export const Routes = mysqlTable(
  "routes",
  {
    id: autoGeneratedId(),
    isActive: boolean("is_active").default(true).notNull(),
    name: varchar("name", { length: 150 }).notNull(),
    code: varchar("code", { length: 50 }).notNull(),
    ownership: routeOwnershipEnum("ownership").notNull(),
    distributorId: varchar("distributor_id", {
      length: 36,
    }),
    organizationId: char("organization_id", { length: 10 })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    territoryId: char("territory_id", { length: 10 })
      .notNull()
      .references(() => Territories.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),

    ...tableMetaData("ROUT"),
  },
  (table) => [
    uniqueIndex("routes_org_code_unique").on(table.organizationId, table.code),
    index("routes_territory_idx").on(table.territoryId),
  ],
);

export const RoutesRelations = relations(Routes, ({ one, many }) => ({
  territory: one(Territories, {
    fields: [Routes.organizationId],
    references: [Territories.id],
  }),
  organization: many(Organizations),
  associatedUsers: many(Users),
}));

/* =========================================================
  MR TERRITORY / ROUTE ASSIGNMENT (M-N RELATIONS)
========================================================= */

export const UserTerritories = mysqlTable(
  "user_territories",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => Users.id, {
        onDelete: "cascade",
      }),
    territoryId: char("territory_id", { length: 10 })
      .notNull()
      .references(() => Territories.id, {
        onDelete: "cascade",
      }),
    assignedFrom: date("assigned_from"),
    assignedTo: date("assigned_to"),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USTE"),
  },
  (table) => [
    primaryKey({
      name: "useers_assigned_territories",
      columns: [table.userId, table.territoryId],
    }),
  ],
);

export const UserRoutes = mysqlTable(
  "user_routes",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => Users.id, {
        onDelete: "cascade",
      }),
    routeId: char("route_id", { length: 10 })
      .notNull()
      .references(() => Routes.id, {
        onDelete: "cascade",
      }),
    assignedFrom: date("assigned_from"),
    assignedTo: date("assigned_to"),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USRT"),
  },
  (table) => [
    primaryKey({
      name: "useers_assigned_routes",
      columns: [table.userId, table.routeId],
    }),
  ],
);

/* =========================================================
  ROUTE STOPS
========================================================= */

export const RouteStops = mysqlTable(
  "route_stops",
  {
    id: autoGeneratedId(),
    routeId: char("route_id", { length: 10 })
      .notNull()
      .references(() => Routes.id, {
        onDelete: "cascade",
      }),
    customerId: char("customer_id", { length: 10 })
      .notNull()
      .references(() => Customers.id, {
        onDelete: "cascade",
      }),
    sequence: int("sequence").notNull(),
    plannedVisitDurationMinutes: int("planned_visit_duration_minutes"),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("RUST"),
  },
  (table) => [
    uniqueIndex("route_stops_route_sequence_unique").on(
      table.routeId,
      table.sequence,
    ),
    index("route_stops_route_customer_idx").on(table.routeId, table.customerId),
  ],
);

/* =========================================================
  STOCKISTS / DISTRIBUTORS
========================================================= */

export const Stockists = mysqlTable(
  "stockists",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    name: varchar("name", { length: 200 }).notNull(),
    code: varchar("code", { length: 50 }),
    phone: varchar("phone", { length: 30 }),
    email: varchar("email", { length: 255 }),
    address: text("address"),
    city: varchar("city", { length: 100 }),
    district: varchar("district", { length: 100 }),
    state: varchar("state", { length: 100 }),
    pinCode: varchar("pin_code", { length: 10 }),
    drugLicenseNumber: varchar("drug_license_number", {
      length: 100,
    }),
    gstin: varchar("gstin", { length: 20 }),
    pan: varchar("pan", { length: 20 }),
    isDistributor: boolean("is_distributor").default(false).notNull(),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("STKT"),
  },
  (table) => [
    uniqueIndex("stockists_org_code_unique").on(
      table.organizationId,
      table.code,
    ),
  ],
);

/* =========================================================
  MR -> STOCKIST MAPPING
========================================================= */

export const UserStockists = mysqlTable(
  "user_stockists",
  {
    userId: char("user_id", { length: 10 })
      .notNull()
      .references(() => Users.id, {
        onDelete: "cascade",
      }),
    stockistId: char("stockist_id", { length: 10 })
      .notNull()
      .references(() => Stockists.id, {
        onDelete: "cascade",
      }),
    isPrimary: boolean("is_primary").default(false).notNull(),

    ...tableMetaData("USSK"),
  },
  (table) => [
    primaryKey({
      name: "user_stockist",
      columns: [table.userId, table.stockistId],
    }),
  ],
);

/* =========================================================
  CUSTOMERS / DOCTORS / CHEMISTS
========================================================= */

export const Customers = mysqlTable(
  "customers",
  {
    id: autoGeneratedId(),
    organizationId: char("organization_id", {
      length: 10,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    type: customerTypeEnum("type").notNull(),
    name: varchar("name", { length: 200 }).notNull(),
    primaryMobile: varchar("primary_mobile", {
      length: 30,
    }).notNull(),
    secondaryMobile: varchar("secondary_mobile", {
      length: 30,
    }),
    email: varchar("email", { length: 255 }).notNull(),
    address: text("address"),
    pinCode: varchar("pin_code", { length: 10 }),
    drugLicenseNumber: varchar("drug_license_number", {
      length: 100,
    }),
    panNumber: varchar("pan_number", {
      length: 20,
    }),
    gstin: varchar("gstin", {
      length: 20,
    }),
    latitude: decimal("latitude", {
      precision: 10,
      scale: 7,
    }),
    longitude: decimal("longitude", {
      precision: 10,
      scale: 7,
    }),
    isActive: boolean("is_active").default(true).notNull(),
    createdBy: varchar("created_by", {
      length: 36,
    }).references(() => Users.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("CUST"),
  },
  (table) => [
    uniqueIndex("customers_org_primary_mobile_unique").on(
      table.organizationId,
      table.primaryMobile,
    ),
    index("customers_secondary_mobile_idx").on(
      table.organizationId,
      table.secondaryMobile,
    ),
    index("customers_location_idx").on(table.latitude, table.longitude),
  ],
);

/* =========================================================
  CUSTOMER TERRITORY / ROUTE
========================================================= */

export const CustomerAssignments = mysqlTable("customer_assignments", {
  id: autoGeneratedId(),
  customerId: char("customer_id", {
    length: 10,
  })
    .notNull()
    .references(() => Customers.id, {
      onDelete: "cascade",
    }),
  territoryId: char("territory_id", {
    length: 10,
  }).references(() => Territories.id, {
    onDelete: "set null",
  }),
  routeId: char("route_id", {
    length: 10,
  }).references(() => Routes.id, {
    onDelete: "set null",
  }),
  assignedToUserId: char("assigned_to_user_id", {
    length: 10,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  assignedFrom: date("assigned_from"),
  assignedTo: date("assigned_to"),
  isActive: boolean("is_active").default(true).notNull(),

  ...tableMetaData("CUAS"),
});

/* =========================================================
  DOCTOR PROFILE
========================================================= */

export const DoctorProfiles = mysqlTable("doctor_profiles", {
  customerId: char("customer_id", { length: 10 })
    .primaryKey()
    .references(() => Customers.id, {
      onDelete: "cascade",
    }),
  specialist: varchar("specialist", {
    length: 150,
  }),
  chamberName: varchar("chamber_name", {
    length: 200,
  }),
  consultationStartTime: time("consultation_start_time"),
  consultationEndTime: time("consultation_end_time"),
  meetingNotes: text("meeting_notes"),

  ...tableMetaData("DOCS"),
});

/* =========================================================
  DOCTOR AVAILABILITY
========================================================= */

export const DoctorAvailability = mysqlTable("doctor_availability", {
  id: autoGeneratedId(),
  doctorId: char("doctor_id", { length: 10 })
    .notNull()
    .references(() => Customers.id, {
      onDelete: "cascade",
    }),
  dayOfWeek: int("day_of_week").notNull(),
  startTime: time("start_time").notNull(),
  endTime: time("end_time").notNull(),

  ...tableMetaData("DOAV"),
});

/* =========================================================
  PRODUCTS
========================================================= */

export const ProductCategories = mysqlTable("product_categories", {
  id: autoGeneratedId(),
  organizationId: char("organization_id", {
    length: 10,
  })
    .notNull()
    .references(() => Organizations.id, {
      onDelete: "cascade",
    }),
  name: varchar("name", { length: 150 }).notNull(),
  description: text("description"),
  isActive: boolean("is_active").default(true).notNull(),

  ...tableMetaData("PRCT"),
});

export const Products = mysqlTable(
  "products",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    categoryId: varchar("category_id", {
      length: 36,
    }).references(() => ProductCategories.id, {
      onDelete: "set null",
    }),
    name: varchar("name", { length: 200 }).notNull(),
    sku: varchar("sku", { length: 100 }).notNull(),
    genericName: varchar("generic_name", {
      length: 200,
    }),
    strength: varchar("strength", {
      length: 100,
    }),
    dosageForm: varchar("dosage_form", {
      length: 100,
    }),
    packSize: varchar("pack_size", {
      length: 100,
    }),
    unit: varchar("unit", {
      length: 50,
    }),
    description: text("description"),
    benefits: text("benefits"),
    usageInformation: text("usage_information"),
    mrp: decimal("mrp", {
      precision: 14,
      scale: 2,
    }).notNull(),
    taxRate: decimal("tax_rate", {
      precision: 6,
      scale: 2,
    })
      .default("0")
      .notNull(),
    isActive: boolean("is_active").default(true).notNull(),

    ...tableMetaData("PROD"),
  },
  (table) => [
    uniqueIndex("products_org_sku_unique").on(table.organizationId, table.sku),
    index("products_name_idx").on(table.organizationId, table.name),
  ],
);

/* =========================================================
  PRODUCT MEDIA / VISUALIZATION
========================================================= */

export const ProductMedia = mysqlTable("product_media", {
  id: autoGeneratedId(),
  productId: varchar("product_id", { length: 36 })
    .notNull()
    .references(() => Products.id, {
      onDelete: "cascade",
    }),
  mediaId: varchar("media_id", { length: 36 })
    .notNull()
    .references(() => MediaFiles.id, {
      onDelete: "cascade",
    }),
  sortOrder: int("sort_order").default(0).notNull(),
  isPrimary: boolean("is_primary").default(false).notNull(),

  ...tableMetaData("PRMD"),
});

/* =========================================================
  DOCTOR PRODUCT PREFERENCES
========================================================= */

export const DoctorProductPreferences = mysqlTable(
  "doctor_product_preferences",
  {
    doctorId: varchar("doctor_id", { length: 36 })
      .notNull()
      .references(() => Customers.id, {
        onDelete: "cascade",
      }),
    productId: varchar("product_id", { length: 36 })
      .notNull()
      .references(() => Products.id, {
        onDelete: "cascade",
      }),
    preferenceLevel: int("preference_level").default(1).notNull(),
    notes: text("notes"),
    createdBy: varchar("created_by", {
      length: 36,
    }).references(() => Users.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("DPPR"),
  },
  (table) => [
    primaryKey({
      name: "doctor_with_product",
      columns: [table.doctorId, table.productId],
    }),
  ],
);

/* =========================================================
  PRODUCT PRICING
========================================================= */

export const ProductPrices = mysqlTable("product_prices", {
  id: autoGeneratedId(),
  productId: varchar("product_id", { length: 36 })
    .notNull()
    .references(() => Products.id, {
      onDelete: "cascade",
    }),
  stockistId: varchar("stockist_id", {
    length: 36,
  }).references(() => Stockists.id, {
    onDelete: "cascade",
  }),
  sellingPrice: decimal("selling_price", {
    precision: 14,
    scale: 2,
  }).notNull(),
  effectiveFrom: date("effective_from").notNull(),
  effectiveTo: date("effective_to"),

  ...tableMetaData("PRPR"),
});

/* =========================================================
  BATCHES
========================================================= */

export const ProductBatches = mysqlTable(
  "product_batches",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    productId: varchar("product_id", { length: 36 })
      .notNull()
      .references(() => Products.id, {
        onDelete: "restrict",
      }),
    batchNumber: varchar("batch_number", {
      length: 100,
    }).notNull(),
    manufacturingDate: date("manufacturing_date"),
    expiryDate: date("expiry_date").notNull(),
    mrp: decimal("mrp", {
      precision: 14,
      scale: 2,
    }).notNull(),
    purchasePrice: decimal("purchase_price", {
      precision: 14,
      scale: 2,
    }),
    status: batchStatusEnum("status").default("ACTIVE").notNull(),

    ...tableMetaData("PRBT"),
  },
  (table) => [
    uniqueIndex("product_batches_product_batch_unique").on(
      table.productId,
      table.batchNumber,
    ),
    index("product_batches_expiry_idx").on(table.expiryDate),
  ],
);

/* =========================================================
  STOCKIST INVENTORY
========================================================= */

export const StockistInventory = mysqlTable(
  "stockist_inventory",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    stockistId: varchar("stockist_id", {
      length: 36,
    })
      .notNull()
      .references(() => Stockists.id, {
        onDelete: "cascade",
      }),
    productId: varchar("product_id", {
      length: 36,
    })
      .notNull()
      .references(() => Products.id, {
        onDelete: "cascade",
      }),
    batchId: varchar("batch_id", {
      length: 36,
    })
      .notNull()
      .references(() => ProductBatches.id, {
        onDelete: "restrict",
      }),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),
    reservedQuantity: decimal("reserved_quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),

    ...tableMetaData("SKIV"),
  },
  (table) => [
    uniqueIndex("stockist_inventory_unique").on(
      table.stockistId,
      table.batchId,
    ),
    index("stockist_inventory_product_idx").on(
      table.stockistId,
      table.productId,
    ),
  ],
);

/* =========================================================
  MASTER / COMPANY WAREHOUSE INVENTORY
========================================================= */

export const MasterInventory = mysqlTable(
  "master_inventory",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    productId: varchar("product_id", {
      length: 36,
    })
      .notNull()
      .references(() => Products.id, {
        onDelete: "cascade",
      }),
    batchId: varchar("batch_id", {
      length: 36,
    })
      .notNull()
      .references(() => ProductBatches.id, {
        onDelete: "restrict",
      }),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),
    reservedQuantity: decimal("reserved_quantity", {
      precision: 14,
      scale: 3,
    })
      .default("0")
      .notNull(),

    ...tableMetaData("MAIN"),
  },
  (table) => [
    uniqueIndex("master_inventory_batch_unique").on(
      table.organizationId,
      table.batchId,
    ),
  ],
);

/* =========================================================
  INVENTORY MOVEMENTS
========================================================= */

export const InventoryMovements = mysqlTable(
  "inventory_movements",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    stockistId: varchar("stockist_id", {
      length: 36,
    }).references(() => Stockists.id, {
      onDelete: "set null",
    }),
    productId: varchar("product_id", {
      length: 36,
    })
      .notNull()
      .references(() => Products.id, {
        onDelete: "restrict",
      }),
    batchId: varchar("batch_id", {
      length: 36,
    })
      .notNull()
      .references(() => ProductBatches.id, {
        onDelete: "restrict",
      }),
    type: inventoryMovementTypeEnum("type").notNull(),
    quantity: decimal("quantity", {
      precision: 14,
      scale: 3,
    }).notNull(),
    referenceType: varchar("reference_type", {
      length: 50,
    }),
    referenceId: varchar("reference_id", {
      length: 36,
    }),
    notes: text("notes"),
    createdBy: varchar("created_by", {
      length: 36,
    }).references(() => Users.id, {
      onDelete: "set null",
    }),

    ...tableMetaData("INMV"),
  },
  (table) => [
    index("inventory_movements_stockist_idx").on(table.stockistId),
    index("inventory_movements_product_batch_idx").on(
      table.productId,
      table.batchId,
    ),
    index("inventory_movements_created_at_idx").on(table.createdAt),
  ],
);

/* =========================================================
  STOCK TRANSFERS
========================================================= */

export const StockTransfers = mysqlTable("stock_transfers", {
  id: autoGeneratedId(),
  organizationId: varchar("organization_id", {
    length: 36,
  })
    .notNull()
    .references(() => Organizations.id, {
      onDelete: "cascade",
    }),
  fromStockistId: varchar("from_stockist_id", {
    length: 36,
  }).references(() => Stockists.id, {
    onDelete: "set null",
  }),
  toStockistId: varchar("to_stockist_id", {
    length: 36,
  }).references(() => Stockists.id, {
    onDelete: "set null",
  }),
  status: stockTransferStatusEnum("status").default("DRAFT").notNull(),
  requestedBy: varchar("requested_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  approvedBy: varchar("approved_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  approvedAt: timestamp("approved_at"),
  notes: text("notes"),

  ...tableMetaData("STTR"),
});

export const StockTransferItems = mysqlTable("stock_transfer_items", {
  id: autoGeneratedId(),
  transferId: varchar("transfer_id", {
    length: 36,
  })
    .notNull()
    .references(() => StockTransfers.id, {
      onDelete: "cascade",
    }),
  productId: varchar("product_id", {
    length: 36,
  })
    .notNull()
    .references(() => Products.id, {
      onDelete: "restrict",
    }),
  batchId: varchar("batch_id", {
    length: 36,
  })
    .notNull()
    .references(() => ProductBatches.id, {
      onDelete: "restrict",
    }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),

  ...tableMetaData("STIT"),
});

/* =========================================================
  ATTENDANCE / DAY LOG
========================================================= */

export const FieldDays = mysqlTable(
  "field_days",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    userId: varchar("user_id", {
      length: 36,
    })
      .notNull()
      .references(() => Users.id, {
        onDelete: "cascade",
      }),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    workDate: date("work_date").notNull(),
    status: dayStatusEnum("status").default("OPEN").notNull(),
    travelMode: travelModeEnum("travel_mode"),
    openingOdometer: decimal("opening_odometer", {
      precision: 12,
      scale: 2,
    }),
    closingOdometer: decimal("closing_odometer", {
      precision: 12,
      scale: 2,
    }),
    openingOdometerPhotoId: varchar("opening_odometer_photo_id", {
      length: 36,
    }).references(() => MediaFiles.id, {
      onDelete: "set null",
    }),
    closingOdometerPhotoId: varchar("closing_odometer_photo_id", {
      length: 36,
    }).references(() => MediaFiles.id, {
      onDelete: "set null",
    }),
    startSelfieId: varchar("start_selfie_id", {
      length: 36,
    }).references(() => MediaFiles.id, {
      onDelete: "set null",
    }),
    endSelfieId: varchar("end_selfie_id", {
      length: 36,
    }).references(() => MediaFiles.id, {
      onDelete: "set null",
    }),
    startLatitude: decimal("start_latitude", {
      precision: 10,
      scale: 7,
    }),
    startLongitude: decimal("start_longitude", {
      precision: 10,
      scale: 7,
    }),
    endLatitude: decimal("end_latitude", {
      precision: 10,
      scale: 7,
    }),
    endLongitude: decimal("end_longitude", {
      precision: 10,
      scale: 7,
    }),
    startedAt: timestamp("started_at"),
    endedAt: timestamp("ended_at"),
    lockedAt: timestamp("locked_at"),

    ...tableMetaData("FLDY"),
  },
  (table) => ({
    userDateUnique: uniqueIndex("field_days_user_date_unique").on(
      table.userId,
      table.workDate,
    ),
    userDateIdx: index("field_days_user_date_idx").on(
      table.userId,
      table.workDate,
    ),
  }),
);

/* =========================================================
  DAY UNLOCK REQUESTS
========================================================= */

export const DayUnlockRequests = mysqlTable("day_unlock_requests", {
  id: autoGeneratedId(),
  fieldDayId: varchar("field_day_id", {
    length: 36,
  })
    .notNull()
    .references(() => FieldDays.id, {
      onDelete: "cascade",
    }),
  requestedBy: varchar("requested_by", {
    length: 36,
  })
    .notNull()
    .references(() => Users.id, {
      onDelete: "restrict",
    }),
  reviewedBy: varchar("reviewed_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  reason: text("reason").notNull(),
  status: approvalStatusEnum("status").default("PENDING").notNull(),
  reviewComment: text("review_comment"),
  reviewedAt: timestamp("reviewed_at"),

  ...tableMetaData("DURQ"),
});

/* =========================================================
  VISITS
========================================================= */

export const Visits = mysqlTable(
  "visits",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    fieldDayId: varchar("field_day_id", {
      length: 36,
    })
      .notNull()
      .references(() => FieldDays.id, {
        onDelete: "cascade",
      }),
    userId: varchar("user_id", {
      length: 36,
    })
      .notNull()
      .references(() => Users.id, {
        onDelete: "cascade",
      }),
    customerId: varchar("customer_id", {
      length: 36,
    })
      .notNull()
      .references(() => Customers.id, {
        onDelete: "restrict",
      }),
    routeId: varchar("route_id", {
      length: 36,
    }).references(() => Routes.id, {
      onDelete: "set null",
    }),
    checkInAt: timestamp("check_in_at").notNull(),
    checkOutAt: timestamp("check_out_at"),
    checkInLatitude: decimal("check_in_latitude", {
      precision: 10,
      scale: 7,
    }).notNull(),
    checkInLongitude: decimal("check_in_longitude", {
      precision: 10,
      scale: 7,
    }).notNull(),
    checkOutLatitude: decimal("check_out_latitude", {
      precision: 10,
      scale: 7,
    }),
    checkOutLongitude: decimal("check_out_longitude", {
      precision: 10,
      scale: 7,
    }),
    accuracyMeters: decimal("accuracy_meters", {
      precision: 10,
      scale: 2,
    }),
    visitPhotoId: varchar("visit_photo_id", {
      length: 36,
    }).references(() => MediaFiles.id, {
      onDelete: "set null",
    }),
    outcome: visitOutcomeEnum("outcome"),
    feedback: text("feedback"),
    remarks: text("remarks"),
    durationSeconds: int("duration_seconds"),

    ...tableMetaData("VIST"),
  },
  (table) => [
    index("visits_user_date_idx").on(table.userId, table.checkInAt),
    index("visits_customer_idx").on(table.customerId),
    index("visits_geo_idx").on(table.checkInLatitude, table.checkInLongitude),
  ],
);

/* =========================================================
  ORDERS
========================================================= */

export const Orders = mysqlTable(
  "orders",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    orderNumber: varchar("order_number", {
      length: 50,
    }).notNull(),
    userId: varchar("user_id", {
      length: 36,
    })
      .notNull()
      .references(() => Users.id, {
        onDelete: "restrict",
      }),
    customerId: varchar("customer_id", {
      length: 36,
    })
      .notNull()
      .references(() => Customers.id, {
        onDelete: "restrict",
      }),
    stockistId: varchar("stockist_id", {
      length: 36,
    })
      .notNull()
      .references(() => Stockists.id, {
        onDelete: "restrict",
      }),
    routeId: varchar("route_id", {
      length: 36,
    }).references(() => Routes.id, {
      onDelete: "set null",
    }),
    visitId: varchar("visit_id", {
      length: 36,
    }).references(() => Visits.id, {
      onDelete: "set null",
    }),
    orderType: orderTypeEnum("order_type").notNull(),
    status: orderStatusEnum("status").default("DRAFT").notNull(),
    paymentStatus: paymentStatusEnum("payment_status")
      .default("PENDING")
      .notNull(),
    subtotal: decimal("subtotal", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    discountAmount: decimal("discount_amount", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    taxAmount: decimal("tax_amount", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    grandTotal: decimal("grand_total", {
      precision: 14,
      scale: 2,
    })
      .default("0")
      .notNull(),
    notes: text("notes"),
    submittedAt: timestamp("submitted_at"),

    ...tableMetaData("ORDR"),
  },
  (table) => [
    uniqueIndex("orders_org_number_unique").on(
      table.organizationId,
      table.orderNumber,
    ),
    index("orders_user_idx").on(table.userId),
    index("orders_customer_idx").on(table.customerId),
    index("orders_stockist_idx").on(table.stockistId),
    index("orders_status_idx").on(table.status),
  ],
);

/* =========================================================
  ORDER ITEMS
========================================================= */

export const OrderItems = mysqlTable("order_items", {
  id: autoGeneratedId(),
  orderId: varchar("order_id", {
    length: 36,
  })
    .notNull()
    .references(() => Orders.id, {
      onDelete: "cascade",
    }),
  productId: varchar("product_id", {
    length: 36,
  })
    .notNull()
    .references(() => Products.id, {
      onDelete: "restrict",
    }),
  batchId: varchar("batch_id", {
    length: 36,
  }).references(() => ProductBatches.id, {
    onDelete: "restrict",
  }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),
  unitPrice: decimal("unit_price", {
    precision: 14,
    scale: 2,
  }).notNull(),
  discountPercent: decimal("discount_percent", {
    precision: 6,
    scale: 2,
  })
    .default("0")
    .notNull(),
  discountAmount: decimal("discount_amount", {
    precision: 14,
    scale: 2,
  })
    .default("0")
    .notNull(),
  taxPercent: decimal("tax_percent", {
    precision: 6,
    scale: 2,
  })
    .default("0")
    .notNull(),
  taxAmount: decimal("tax_amount", {
    precision: 14,
    scale: 2,
  })
    .default("0")
    .notNull(),
  lineTotal: decimal("line_total", {
    precision: 14,
    scale: 2,
  }).notNull(),

  ...tableMetaData("ORIT"),
});

/* =========================================================
  ORDER FULFILLMENT
========================================================= */

export const OrderFulfillments = mysqlTable("order_fulfillments", {
  id: autoGeneratedId(),
  orderId: varchar("order_id", {
    length: 36,
  })
    .notNull()
    .references(() => Orders.id, {
      onDelete: "cascade",
    }),
  status: fulfillmentStatusEnum("status").default("PENDING").notNull(),
  invoiceNumber: varchar("invoice_number", {
    length: 100,
  }),
  invoiceDate: date("invoice_date"),
  invoiceUrl: text("invoice_url"),
  dispatchedAt: timestamp("dispatched_at"),
  deliveredAt: timestamp("delivered_at"),
  deliveryConfirmedBy: varchar("delivery_confirmed_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  deliveryRemarks: text("delivery_remarks"),

  ...tableMetaData("ORFL"),
});

/* =========================================================
  ORDER STATUS HISTORY
========================================================= */

export const OrderStatusHistory = mysqlTable("order_status_history", {
  id: autoGeneratedId(),
  orderId: varchar("order_id", {
    length: 36,
  })
    .notNull()
    .references(() => Orders.id, {
      onDelete: "cascade",
    }),
  oldStatus: orderStatusEnum("old_status"),
  newStatus: orderStatusEnum("new_status").notNull(),
  changedBy: varchar("changed_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  comment: text("comment"),

  ...tableMetaData("ORSH"),
});

/* =========================================================
  PAYMENTS / COLLECTION
========================================================= */

export const Payments = mysqlTable("payments", {
  id: autoGeneratedId(),
  organizationId: varchar("organization_id", {
    length: 36,
  })
    .notNull()
    .references(() => Organizations.id, {
      onDelete: "cascade",
    }),
  orderId: varchar("order_id", {
    length: 36,
  }).references(() => Orders.id, {
    onDelete: "set null",
  }),
  customerId: varchar("customer_id", {
    length: 36,
  })
    .notNull()
    .references(() => Customers.id, {
      onDelete: "restrict",
    }),
  collectedBy: varchar("collected_by", {
    length: 36,
  })
    .notNull()
    .references(() => Users.id, {
      onDelete: "restrict",
    }),
  amount: decimal("amount", {
    precision: 14,
    scale: 2,
  }).notNull(),
  method: paymentMethodEnum("method").notNull(),
  status: paymentStatusEnum("status").default("PAID").notNull(),
  transactionReference: varchar("transaction_reference", { length: 150 }),
  collectedAt: timestamp("collected_at").defaultNow().notNull(),
  remarks: text("remarks"),

  ...tableMetaData("PYMT"),
});

/* =========================================================
  COLLECTION HANDOVER
========================================================= */

export const CollectionHandovers = mysqlTable("collection_handovers", {
  id: autoGeneratedId(),
  userId: varchar("user_id", {
    length: 36,
  })
    .notNull()
    .references(() => Users.id, {
      onDelete: "restrict",
    }),
  stockistId: varchar("stockist_id", {
    length: 36,
  })
    .notNull()
    .references(() => Stockists.id, {
      onDelete: "restrict",
    }),
  amount: decimal("amount", {
    precision: 14,
    scale: 2,
  }).notNull(),
  status: collectionStatusEnum("status").default("PENDING").notNull(),
  handedOverAt: timestamp("handed_over_at"),
  verifiedBy: varchar("verified_by", {
    length: 36,
  }).references(() => Users.id, {
    onDelete: "set null",
  }),
  verifiedAt: timestamp("verified_at"),
  remarks: text("remarks"),

  ...tableMetaData("COHO"),
});

/* =========================================================
  EXPIRY / WASTAGE
========================================================= */

export const ExpiryWastageEntries = mysqlTable("expiry_wastage_entries", {
  id: autoGeneratedId(),

  stockistId: varchar("stockist_id", {
    length: 36,
  }).references(() => Stockists.id, {
    onDelete: "set null",
  }),
  productId: varchar("product_id", {
    length: 36,
  })
    .notNull()
    .references(() => Products.id, {
      onDelete: "restrict",
    }),
  batchId: varchar("batch_id", {
    length: 36,
  })
    .notNull()
    .references(() => ProductBatches.id, {
      onDelete: "restrict",
    }),
  quantity: decimal("quantity", {
    precision: 14,
    scale: 3,
  }).notNull(),
  reason: varchar("reason", {
    length: 150,
  }).notNull(),
  remarks: text("remarks"),
  enteredBy: varchar("entered_by", {
    length: 36,
  })
    .notNull()
    .references(() => Users.id, {
      onDelete: "restrict",
    }),

  ...tableMetaData("EXWS"),
});

/* =========================================================
  DOCTOR / CUSTOMER FOLLOW UPS
========================================================= */

export const CustomerFollowUps = mysqlTable("customer_follow_ups", {
  id: autoGeneratedId(),

  customerId: varchar("customer_id", {
    length: 36,
  })
    .notNull()
    .references(() => Customers.id, {
      onDelete: "cascade",
    }),

  assignedTo: varchar("assigned_to", {
    length: 36,
  })
    .notNull()
    .references(() => Users.id, {
      onDelete: "restrict",
    }),

  visitId: varchar("visit_id", {
    length: 36,
  }).references(() => Visits.id, {
    onDelete: "set null",
  }),
  dueDate: date("due_date").notNull(),
  notes: text("notes"),
  completedAt: timestamp("completed_at"),

  ...tableMetaData("CUFU"),
});

/* =========================================================
  AUDIT LOG
========================================================= */

export const AuditLogs = mysqlTable(
  "audit_logs",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    userId: varchar("user_id", {
      length: 36,
    }).references(() => Users.id, {
      onDelete: "set null",
    }),
    action: varchar("action", {
      length: 100,
    }).notNull(),
    entityType: varchar("entity_type", {
      length: 100,
    }).notNull(),
    entityId: varchar("entity_id", {
      length: 36,
    }),
    oldValues: json("old_values"),
    newValues: json("new_values"),
    ipAddress: varchar("ip_address", {
      length: 100,
    }),
    userAgent: text("user_agent"),

    ...tableMetaData("AUDL"),
  },
  (table) => [
    index("audit_logs_entity_idx").on(table.entityType, table.entityId),
    index("audit_logs_user_idx").on(table.userId),
    index("audit_logs_created_at_idx").on(table.createdAt),
  ],
);

/* =========================================================
  APP SETTINGS
========================================================= */

export const OrganizationSettings = mysqlTable(
  "organization_settings",
  {
    id: varchar("id", { length: 36 })
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    organizationId: varchar("organization_id", {
      length: 36,
    })
      .notNull()
      .references(() => Organizations.id, {
        onDelete: "cascade",
      }),
    key: varchar("key", {
      length: 100,
    }).notNull(),
    value: json("value"),

    ...tableMetaData("ORST"),
  },
  (table) => ({
    keyUnique: uniqueIndex("organization_settings_key_unique").on(
      table.organizationId,
      table.key,
    ),
  }),
);
