name: ubique-prod-local

networks:
  ubique-prod-local:
    driver: bridge

services:
  ubique-prod-local-database:
    container_name: ubique-prod-local-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ubique-prod-local
    ports:
      - 11437:3306
    networks:
      - ubique-prod-local
    volumes:
      - database:/var/lib/mysql

  ubique-prod-local-phpmyadmin:
    container_name: ubique-prod-local-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "15668:80"
    environment:
      PMA_HOST: ubique-prod-local-database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - ubique-prod-local-database
    networks:
      - ubique-prod-local

  ubique-prod-local-proxy:
    container_name: ubique-prod-local-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ubique-prod-local
    volumes:
      - ../nginx.secure.prod.local.conf:/etc/nginx/nginx.conf:ro
      - ../localhost-cert.pem:/etc/nginx/certs/localhost-cert.pem:ro
      - ../localhost-key.pem:/etc/nginx/certs/localhost-key.pem:ro

  ubique-web-app:
    container_name: ubique-web-app
    image: "nirvikpurkait/ubique/web-app"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      - "localhost.dev:host-gateway"
      - "storage.localhost.dev:host-gateway"
    env_file:
      - ../.env.production.local
    ports:
      - 12773:3000
    networks:
      - ubique-prod-local
    depends_on:
      - ubique-prod-local-database

  ubique-storage-app:
    container_name: ubique-storage-app
    image: "nirvikpurkait/ubique/storage-app"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      - "localhost.dev:host-gateway"
      - "storage.localhost.dev:host-gateway"
    env_file:
      - ../.env.production.local
    ports:
      - 12039:3000
    networks:
      - ubique-prod-local
    depends_on:
      - ubique-prod-local-database

volumes:
  database: